### ISSUE TITLE
Add ERC 725 interface and reference implementation

### ISSUE THREAD

**Issue by lsaether** [OpenZeppelin/openzeppelin-contracts#1184]
## 🎉 Description

This is a proposal to add the [ERC725](https://github.com/ethereum/EIPs/issues/725) interface and implementation contract to the openzeppelin library. 

- [X ] 📈 This is a feature request.

## 📝 Details

ERC725 is a proxy contract for key management and and execution that handles blockchain identity.

## 👍 Other Information

I will send a PR with the ERC725 interface contract and a reference implementation if this is deemed relevant for the openzeppelin library.

**Comment by Amxx** [comment]
ERC725 changed since this issue was open. It no longer does key management (this was moved to 734).

Both have been stuck in draft for years, and have no adoption. It appear that the original objective of this EIP evolved into the proxy model present in the [lukso whitepaper](https://lukso.network/assets/LUKSO_Whitepaper.pdf).
