### ISSUE TITLE
Support import from syntax

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#1607]
```solidity
import { ERC20 } from "openzeppelin-solidity";
```

This would be very nice I think, but the tooling probably doesn't support it. Truffle needs to know how to resolve the `"openzeppelin-solidity"` import. Node.js solves this by importing the package's main file, or an `index.js` file if it's a directory. We should propose this feature to Truffle first.

**Comment by cameel** [comment]
Looks like Truffle does support this by now.

**Comment by frangio** [comment]
@cameel I think I meant importing from the package (`... from "@openzeppelin/contracts"` now) as opposed to from a specific file. Do you know if that resolves to anything in Truffle or Hardhat?

**Comment by cameel** [comment]
Oh, sorry, I misunderstood the issue. I thought that it was about `import ... from ...` syntax not being supported by frameworks.

I don't think they support that because they would have to be either rewriting imports in user's files or using remappings. As far as I know they do not do either.

That's actually a use case for remappings I haven't thought about before. And it's pretty nifty. Might be worth submitting feature requests in Truffle and Hardhat.

### Details of potential implementation
The naive way of solving this - by just putting a copy of the code under `@openzeppelin/contracts` in Standard JSON input - will not work correctly. It might look like it works in some cases but consider this example:

- `myerc20.sol`
    ```solidity
    import {ERC20} from "@openzeppelin/contracts";

    contract MyERC20 is ERC20 {}
    ```
- `test.sol`
    ```solidity
    import {ERC20} from "@openzeppelin/contracts/token/ERC20/ERC20.sol";
    import {MyERC20} from "myerc20.sol";

    function run(ERC20 token) {}

    function test() {
        run(new MyERC20());
    }
    ```

This will not compile. You will get a very confusing error that looks something like this:
```
Error: Invalid type for argument in function call. Invalid implicit conversion from contract MyERC20 to contract ERC20 requested.
 --> test.sol:8:17:
  |
8 |             run(new MyERC20());
  |   
```

This is because to compiler will see `@openzeppelin/contracts` and `@openzeppelin/contracts/token/ERC20/ERC20.sol` as two distinct source units. There will therefore be two distinct contracts named `ERC20` coming from these source units and it will look like `MyERC20` inherits from a different `ERC20` than the one you're importing.

With remappings though it wouldn't really take much effort on the part of frameworks to implement this - the support for remappings is already in the compiler and they would just have to put them in Standard JSON input:
```json
{
    ...
    "settings": {
        "remappings": [
            ":@openzeppelin/contracts=@openzeppelin/contracts/token/ERC20/ERC20.sol",
            ":solidity-stringutils=solidity-stringutils/src/strings.sol",
            ":solidity-jwt=solidity-jwt/contracts/Base64.sol",
            ...
        ]
    }
}
```
The biggest issue would probably be deciding what to use as the target. Some convention like e.g. having a file named `index.sol` that exposes library API would have to be established.

**Comment by frangio** [comment]
Yes an `index.sol` would do the trick.

I'm going to close this issue since this isn't possible to implement on our end but if you think it could be interesting and feasible and want to raise it with frameworks feel free to tag me or involve me in the conversation.
