### ISSUE TITLE
IERC721 interfaces labelled as contract

### ISSUE THREAD

**Issue by Aniket-Engg** [OpenZeppelin/openzeppelin-contracts#1679]
**🧐 Motivation**

Related File: [IERC721Receiver.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/IERC721Receiver.sol)
It seems possible to make this contract same as defined in ERC721 standard [here](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md).

**📝 Details**
Function in this contract can be labelled as 'external' and it can be declared as an 'interface'.

**Comment by nventuro** [comment]
Hello @Aniket-Engg, thanks for reporting this!

Indeed, I was able to successfully compile the contracts with that change, but I also had to make the `data` argument be located in `calldata` as opposed to `memory` (since `external` functions cannot use it). I'm not sure if this means our function actually wrong in the first place: I've asked the Solidity team on gitter about it.

**Comment by Aniket-Engg** [comment]
Thanks @nventuro  for your efforts. I think @chriseth  [response](https://gitter.im/ethereum/solidity-dev?at=5c9200c1d0133e21e5e48351) on gitter explains that this can be done without any negative impact.

**Comment by nventuro** [comment]
Putting on hold until the next major release as discussed in https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1694.
