### ISSUE TITLE
Add UnorderedKeySet library

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-contracts#1817]
**🧐 Motivation**
Add commonly used mapping key management library.

**📝 Details**
Add the UnorderedKeySet library to OpenZeppelin: https://github.com/rob-Hitchens/UnorderedKeySet

**Comment by frangio** [comment]
Thanks for the suggestion @thegostep!

If I understand correctly `UnorderedKeySet` is essentially an iterable mapping. Is that right?

In particular it provides iteration of one item at a time. I think we'll be inclined against including this feature, because this kind of iteration turns out to not be very useful for smart contracts or dapps. There's been [some discussion recently](https://forum.zeppelin.solutions/t/expose-tokensofowner-method-on-erc721enumerable/888/6?u=frangio) about having _pagination_ in smart contracts, and that's something we think would be a better fit.

**Comment by thegostep** [comment]
Ah interesting, we use iterable mappings quite a bit on the dapp side though do not use it from the smart contracts for obvious reasons. 

Is there an alternative method for dapps to iterate over mappings?

**Comment by frangio** [comment]
>we use iterable mappings quite a bit on the dapp side

Can you share more details on how you do this? Have you run into performance problems with the approach?

>cleanly remove mapping items

Can you expand on this a bit? I don't see any difference from using a mapping by itself.

**Comment by thegostep** [comment]
> Can you share more details on how you do this? Have you run into performance problems with the approach?

Keep a dynamic sized unordered array of the active mapping keys and access with simple getter. Have not run into performance issues yet.

> Can you expand on this a bit? I don't see any difference from using a mapping by itself.

The array of mapping keys allows the dapp to quickly access the list of mapping entries without parsing event logs.

**Comment by nventuro** [comment]
This is basically what `EnumerableSet` and `EnumerableMap` are, right? We're discussing pagination getters in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2296.

I think we can close this issue.
