### ISSUE TITLE
Supply of tokens

### ISSUE THREAD

**Issue by nsingh3905** [OpenZeppelin/openzeppelin-contracts#1833]
So I've made an ERC20 token contract, tested it on etherscan, ive included a constructor which says the name, symbol, decimals. I'm trying to figure out where exactly to put the total supply of tokens that need to be produced. do I do it on etherscan when im verifying code? do i put it in remix  next to the deploy button?. or does etherscan control the supply for us.

**Comment by abcoathup** [comment]
Hi @nsingh3905 

For support questions (rather than Feature Requests or Bug Reports) I suggest that you ask in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/ that way the entire community can help answer your question.

To understand ERC20 supply, I suggest you have a look at the OpenZeppelin Contracts ERC20 documentation:
https://docs.openzeppelin.com/contracts/2.x/tokens#ERC20

If the token has a fixed supply, then it was either hard coded in the constructor or passed as a parameter to the constructor when you deployed the token.  From what you are describing in Remix your contract accepts the initial supply as a parameter to the constructor, so you should set the initial supply value there.

Blockchain explorers will read the value of the `totalSupply()` function of the contract.

**Comment by abcoathup** [comment]
Hi @nsingh3905 
If you need further assistance, please ask in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/

I am closing this issue as it is now a few weeks since the last reply.
