### ISSUE TITLE
IERC721 functions expected to be external

### ISSUE THREAD

**Issue by thecryptofruit** [OpenZeppelin/openzeppelin-contracts#1940]
Any particular reason why IERC721 has functions `public` instead of `external` as per [standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md)?
The standard mentions issues with Solidity ~4.20, but we're far from that now and [Solidity #3038](https://github.com/ethereum/solidity/pull/3038) enforces it.

This situation has been remedied across several other tokens, just not with all :)
E.g. [IERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1263)
or [IERC721Metadata](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1444)

**💻 Environment**
Latest release OpenZeppelin 2.3 , but also newer unreleased.

**📝 Details**
Makes compiler complain if trying to import from multiple interfaces with conflicting overrides (e.g. IERC721, IERC1155).

Thanks for comments ;)

Edit: fixed IERC20 link.

**Comment by frangio** [comment]
Thank you for reporting!

Unfortunately we can't change this since it's a breaking change. See https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1694#issuecomment-476701733.

I'm not sure I understood your note in Details. Can you please share an example of code for which the compiler complains?

**Comment by frangio** [comment]
Sorry, #1694 is specifically about `IERC721Receiver`.

Regarding the `IERC721` interface, we made it a `contract` because we wanted inheritance to express the requirement that all `IERC721`s must implement `IERC165`. Inheritance is not possible to do with `interface`s unfortunately. Since we made them `contract`s we have to make the functions `public`, if we had made them `external` the implementations (`ERC721`) wouldn't be able to make them `public` because the compiler disallows changing visibility in a derived contract.

**Comment by frangio** [comment]
@thecryptofruit That example fails to compile because you're importing from different versions of the library and Remix is downloading two `IERC165` interfaces from different places. It thinks they're two different files that's why it thinks the two definitions conflict. It's not caused by the `public` functions in `IERC721`.

To fix it you can ensure you're using the same commit or tag to download contracts from.
