### ISSUE TITLE
Modular exponentiation precompile wrapper

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#1985]
[EIP 198](https://eips.ethereum.org/EIPS/eip-198) introduced the modular exponentiation precompile, also known as "modexp".

It's a useful primitive for cryptographic operations, which we would like to wrap in a library so that developers can use it without having to write assembly.

One of the challenges is the fact that the precompile receives and returns bignums, i.e. numbers of arbitrary size. In order to provide a good interface, we might need to define a struct to represent bignum types.

**Comment by mw2000** [comment]
Is anyone still working on this? If not I'd like to have a crack at this.

**Comment by mw2000** [comment]
I found this useful function on StackExchange that could be the solution to this:

`
    function modExp(uint256 _b, uint256 _e, uint256 _m) public returns (uint256 result) {
        assembly {
            // Free memory pointer
            let pointer := mload(0x40)

            // Define length of base, exponent and modulus. 0x20 == 32 bytes
            mstore(pointer, 0x20)
            mstore(add(pointer, 0x20), 0x20)
            mstore(add(pointer, 0x40), 0x20)

            // Define variables base, exponent and modulus
            mstore(add(pointer, 0x60), _b)
            mstore(add(pointer, 0x80), _e)
            mstore(add(pointer, 0xa0), _m)

            // Store the result
            let value := mload(0xc0)

            // Call the precompiled contract 0x05 = bigModExp
            if iszero(call(not(0), 0x05, 0, pointer, 0xc0, value, 0x20)) {
                revert(0, 0)
            }

            result := mload(value)
        }
    }
`

https://ethereum.stackexchange.com/questions/71565/verifying-modular-exponentiation-operation-in-etherum

**Comment by ernestognw** [comment]
I'm not sure if https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3298 's implementation is actually useful in the majority of the cases. The main reason why I see developers using `modexp` is because they're working with RSA signatures (not sure if there are other cases).

When working with RSA signatures, a private key consists of a modulus `m` and an exponent `e`. So for producing a signature, a signer should get a digest of the signed message and then do `modexp(digest, e, m)` in order to get a signature.

Similarly, for verifying it's needed to do `modexp(signature, e, m)`.

Both operations don't fit in an `uint256` since typically the values of both `e` and `m` are typically 3072 bits (for 128-bit security).

Although RSA signatures have never been popular on Ethereum, with the new Account Abstraction trend it can be used as an alternative authorization mechanism. So, I'm afraid that this implementation wouldn't solve that particular use case.
If there's another use case justifying this current implementation, we can consider merging it.
