### ISSUE TITLE
Support for Solidity 0.6.0

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/openzeppelin-contracts#2028]
**🧐 Motivation**

OpenZeppelin Contracts support for Solidity 0.6 has been requested in the forum: https://forum.openzeppelin.com/t/when-solidity-0-6-0-support-for-oz-contracts-library/1948

**📝 Details**

Create a version of OpenZeppelin Contracts with support for [Solidity 0.6](https://github.com/ethereum/solidity/releases/tag/v0.6.0).

**Comment by frangio** [comment]
0.6 includes many things that will probably result in a new major release of the OpenZeppelin Contracts.

Some snippets from the release notes that I think will be relevant for us:

> Language features
> - Allow explicit conversions from `address` to `address payable` via `payable(...)`.

We'll want to remove `Address.toPayable`.

> - Allow global enums and structs.

We should review the structs that we have and see if they should be made global.

> - Introduce virtual and override keywords.

This is probably the biggest one, as we will have to decide what functions should be overrideable. The sentiment in the team is that we should be tolerant of extension, because users already expect this, and so a lot of things will have to be overrideable.

> - Introduce try/catch-statement

We have some instances where we use `.call` only because we need to catch any potential reverts. This feature will be very useful, and likely remove all manual `.call`s or `.staticall`s.

>Compiler Features:
> - Allow revert strings to be stripped from the binary using the --revert-strings option or the settings.debug.revertStrings setting.

We might want to use this flag when compiling the artifacts that are included in the package.

**Comment by frangio** [comment]
There's a very useful "how to update your code" guide in the Solidity docs. We should also include this in our release notes when we update to 0.6.

https://solidity.readthedocs.io/en/v0.6.0/060-breaking-changes.html#how-to-update-your-code

**Comment by thecircleoflifefree** [comment]
Is there an estimate ETA for the official support? Will it set before or after Q2?

**Comment by abcoathup** [comment]
Hi @thecircleoflifefree,

There isn't an estimate yet.  I will update here when I know an ETA for supporting Solidity 0.6.

**Comment by frangio** [comment]
@thecircleoflifefree This will definitely happen before Q2, and most likely during January. We are analyzing this and will post as soon as we have any estimates.

**Comment by NTTMai** [comment]
Hey guys, i want to work on this issue

**Comment by gitpusha** [comment]
@frangio - one thing that might also be relevant to you ( I found it to be relevant for `buidler`) is the `solidity-parser-antlr` package current incompatibility with `solc 0.6`

I opened an issue regarding the solc 0.6 array slicing syntax in their repo: https://github.com/federicobond/solidity-parser-antlr/issues/96

**Comment by frangio** [comment]
Very interesting @gitpusha, thanks for sharing! The bit about `SafeERC20` is particularly interesting.

**Comment by abcoathup** [comment]
@gitpusha @thecircleoflifefree and everyone following this issue, I suggest joining the discussion in the forum on adoption of virtual functions:
https://forum.openzeppelin.com/t/how-we-plan-to-adopt-solidity-0-6-virtual-functions/2063

**Comment by GNSPS** [comment]
Hey guys!

Just dropping here a message about the parser. We at ConsenSys Diligence have just taken up its maintenance. Find an updated 0.6.0 version here: https://github.com/consensys/solidity-parser-antlr

**Comment by abcoathup** [comment]
Solidity 0.6 is part of [Contracts Roadmap: January - March 2020](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2068)

Also see WIP PR: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2063

**Comment by abcoathup** [comment]
Hi @gitpusha, @thecircleoflifefree and anyone following this Issue:

OpenZeppelin Contracts were migrated to Solidity 0.6 in [OpenZeppelin Contracts v3.0 Beta](https://forum.openzeppelin.com/t/openzeppelin-contracts-v3-0-beta-release/2256)

Would appreciate if you can give the Beta a try and let us know what you think in the Community Forum!
