### ISSUE TITLE
In transferFrom, should allowance be called before transfer?

### ISSUE THREAD

**Issue by mikephul** [OpenZeppelin/openzeppelin-contracts#2030]
Sorry, this is more of the question rather than a feature request or bug report. 🙏

Referring to this commit https://github.com/OpenZeppelin/openzeppelin-contracts/commit/3a5da758767cfbcf256bdd147c56dbb0a2541569#diff-6202e31fca333ecfb19d878145bc8db5

The `_allowed` method is moved to be after `_transfer`. What is the rationale behind that @nventuro? (The allowance used to be reduced before doing the transfer.)
![image](https://user-images.githubusercontent.com/2575012/71337706-51b34980-257f-11ea-8f1b-88401ea3fd0d.png)

Should possible further actions that depend on allowance be checked by deducting the allowance first before committing to the actions?

**Comment by nventuro** [comment]
Hm, interesting. Thanks for opening this @mikephul!

In the case of `ERC20`, the order is irrelevant because `_transfer` and `_approve` are independent and never call any other contract: they are executed atomically.

_However_, this is very relevant for users that intent to override `_transfer` or `_approve` with their own implementations: we should be clear about the order in which these things happen. cc @frangio

**Comment by decentralMind** [comment]
Also calling _allowed method after _transfer uses more gas.

Also, similar issue with _burnFrom method.

**Comment by nventuro** [comment]
>Also calling _allowed method after _transfer uses more gas.

Could you expand a bit on this point? Have you performed gas measurements with both orderings?

**Comment by decentralMind** [comment]
> Could you expand a bit on this point? Have you performed gas measurements with both orderings?

I tested with following simple code.
```

pragma solidity ^0.5.0;

import "./SafeMath.sol";

contract Check {
    using SafeMath for uint256;

    uint public num = 2;
    
     function afterNum() public returns(bool) {
        num = 1;
        num.sub(2, "error");
        return true;
    }
    
    function beforeNum() public returns(bool) {
        num.sub(2, "error");
        num = 1;
        return true;
    }
}

Tested on Ropsten network.

Gas used by afterNum method is 27,543.
[](https://ropsten.etherscan.io/tx/0x7bca71da334c3178e23db1322b8bdbab511c5878068bedd121434d5c2770aac1
)
Gas used by beforeNum method is 27,307. 
[](https://ropsten.etherscan.io/tx/0x7bca71da334c3178e23db1322b8bdbab511c5878068bedd121434d5c2770aac1)

```

**Comment by decentralMind** [comment]
> Could you expand a bit on this point? Have you performed gas measurements with both orderings?

Please check the updated code, previously I posted the wrong one.

**Comment by decentralMind** [comment]
Today I performed the gas measurement on Rinkeby testnet with openzeppelin ERC20.sol code

_allowed method after  _transfer used 53,242 gas.
[](https://rinkeby.etherscan.io/tx/0x7808911a515ac4b5b99674cccf593a1455258ae7b052233a5916c08e9339fe00)


_allowed method before  _transfer used 23,980 gas.
[](https://rinkeby.etherscan.io/tx/0x8e7bb68b011cd48218db4979f8ff8e781b7680e82910a728a3edf0ec295cf770)

Again, I'm just reporting gas measurement, I'm qualified enough to point out the flaw yet.

**Comment by nventuro** [comment]
The 30 gas difference (27,543 and 27,573) is strange, but extremely small (0.1%), and likely due to the compiler not doing a good enough job: we shouldn't change the source code based on this sort of observed behavior, specially considering we don't understand _why_ the gas cost is different in the first place, and if it will eventually change.

The big gas cost difference you show in rinkeby is likely due to storage slots being already initialized, which causes the cost of `sstore` to be much lower (5k vs 20k).

Thanks for the analysis @decentralMind!
