### ISSUE TITLE
Unable to import OpenZeppelin multiple contract in the old version of remix. Which was working till 20/12/1019 

### ISSUE THREAD

**Issue by pranavdaa** [OpenZeppelin/openzeppelin-contracts#2032]
I was using multiple contracts of openzappeline for deployment of erc20 detail contract. But suddenly remix stopped giving support for the same. IT is also not working even in the newer IDE of Remix. Please check it out and let me .

FOR Newer version - 
![image](https://user-images.githubusercontent.com/38764142/71409740-a1ba0b00-2668-11ea-8aca-7ae81116c4ae.png)

For older version, the problem is import is not being recognized.
![image](https://user-images.githubusercontent.com/38764142/71409893-273dbb00-2669-11ea-9a07-9e9d8e343a51.png)
Please solve the problem. It might be from the remix side also but still let  me know. This has made me stuck for 3 days now.

**Comment by frangio** [comment]
Hi @pranavdaa. Next time please make sure to share your code in text version so that we can more easily copy-paste it to try to reproduce the issue.

**Comment by frangio** [comment]
Hi @pranavdaa! Next time please make sure to share your code in text version so that we can more easily copy-paste it to try to reproduce the issue.

It seems that Remix is having issues resolving transitive imports. I was able to get this to work by manually importing everything.

Please do not use the `master` branch, use the tagged releases, like in the following snippet.

```solidity
pragma solidity ^0.5.0;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/token/ERC20/ERC20.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/GSN/Context.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/math/SafeMath.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/utils/ReentrancyGuard.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/crowdsale/Crowdsale.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/ownership/Ownable.sol";

contract MintableCrodsale is Crowdsale, Ownable {}
```

Let me know if this works for you.

**Comment by pranavdaa** [comment]
HI @frangio . Sorry for the inappropriate. And thx for the help. Can you please provide me the Code instead of the screenshot.If possible!!!

**Comment by frangio** [comment]
You should be able to copy my snippet! It's text.

**Comment by pranavdaa** [comment]
It worked. Thanks for the help. !!

**Comment by buckysballs** [comment]
Nothing above currently working with Remix. I was able to successfully compile just fine a few months ago (December) via `import "https://github.com/OpenZeppelin/openzeppelin-solidity/contracts/ownership/Ownable.sol";`

Anyone else having success with remix?

**Comment by icculp** [comment]
I have had no luck manually importing anything. 

Error: Could not find https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol from any sources; imported from /home/ian/Minter_v1/contracts/Minter.sol

**Comment by abcoathup** [comment]
Hi @icculp,

I assume you are using GitHub imports in Remix.  For Truffle and Hardhat we should use npm imports.

Note: You should only use code published in an official release of OpenZeppelin Contracts, the latest release is 3.4. When importing via GitHub on Remix you can specify the release tag, (otherwise you will get the latest code in the master branch which is OpenZeppelin Contracts 4.0 Beta).

Can you try the simple ERC20 example in the forum: https://forum.openzeppelin.com/t/deploy-a-simple-erc20-token-in-remix/1203

I recommend posting in the community forum, so that anyone in the community can answer.

**Comment by Amxx** [comment]
@icculp Just like the author of this PR, you are pointing to code on the master branch, which changed recently in preparation for the 4.0 release.

You will find solutions to this issue in Fran's post: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2032#issuecomment-568757498
