### ISSUE TITLE
Swapping ERC20 tokens

### ISSUE THREAD

**Issue by pranavdaa** [OpenZeppelin/openzeppelin-contracts#2034]
**🧐 Motivation**
There is no current contract to swap. we have to use Kybernetwork or related stuff for exchange of token . Can you guys figure it out if we can make a contract for this.WOuld love to give my inputs.

**Comment by frangio** [comment]
Take a look at [`ERC20Migrator`](https://docs.openzeppelin.com/contracts/2.x/api/drafts#ERC20Migrator). It's not exactly what you're asking for because it was built for migrating from one ERC20 to another. So it only works with a 1:1 ratio and in only one direction.

**Comment by pranavdaa** [comment]
Actually while trying to implement token swap using OPenZappelin.Did the following-

```
pragma solidity ^0.5.0;

import "github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20/ERC20.sol";
import "github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol";
import "github.com/OpenZeppelin/zeppelin-solidity/contracts/token/ERC20/ERC20Burnable.sol";
import "github.com/OpenZeppelin/zeppelin-solidity/contracts/ownership/Ownable.sol";


contract TokenSwap is Ownable {

    ERC20Burnable futures;
    ERC20 target;

    event Swap(address from, uint amount);

    constructor(address _futures, address _target) public {
        futures = ERC20Burnable(_futures);
        target = ERC20(_target);
    }

    function swap(uint _amount) public {
      address _from = msg.sender;
      futures.burnFrom(_from, _amount);
      emit Swap(_from, _amount);
    }

}
```


But the swap function shows Gas Estimation Fail.
What asper you should be the Target address and future address for this contract to work.
@frangio

**Comment by abcoathup** [comment]
Hi @pranavdaa,

I recommend moving this discussion to the Community Forum.  It would be great if you post some more detail there of what you are looking to do, then it is more visible to the entire community: https://forum.openzeppelin.com/

----

Note: You should only use code published in an official release of OpenZeppelin Contracts, the latest release is 2.4. When importing via GitHub on Remix you can specify the release tag, (otherwise you will get the latest code in the master branch). The example below imports v2.4.0.

```
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v2.4.0/contracts/token/ERC20/ERC20.sol";
```

**Comment by abcoathup** [comment]
Hi @pranavdaa,

I suggest posting in the Community Forum on swapping ERC20 tokens: https://forum.openzeppelin.com/

I am closing this Issue and we can pick up the discussion in the Community Forum.
