### ISSUE TITLE
Add Killable to lifecycle

### ISSUE THREAD

**Issue by Akira-Taniguchi** [OpenZeppelin/openzeppelin-contracts#2044]
**🧐 Motivation**
> Is your feature request related to a specific problem? Is it just a crazy idea? Tell us about it! 

Related to a specific issue

**📝 Details**
>Please describe your feature request in detail. 

I want to add Killable.sol under the lifecycle package
for example...

```
pragma solidity ^0.5.0;

contract Killable {
	address payable public _owner;

	constructor() internal {
		_owner = msg.sender;
	}

	function kill() public {
		require(msg.sender == _owner, "only owner method");
		selfdestruct(_owner);
	}
}
```

**Comment by abcoathup** [comment]
Hi @Akira-Taniguchi ,

Thanks for starting this discussion. We may want to move this to the community forum (https://forum.openzeppelin.com/), as it is easier for the entire community to see and hence participate.

Are you using Destructable contracts yourself or have you some examples of them being used?

**Comment by Akira-Taniguchi** [comment]
>Are you using Destructable contracts yourself or have you some examples of them being used?

yes, I am using Destructable contracts myself.

[Killable contract]
https://github.com/dev-protocol/protocol/blob/master/contracts/src/common/lifecycle/Killable.sol

[Usage examples]
https://github.com/dev-protocol/protocol/blob/master/contracts/src/policy/Policy.sol#L12

@abcoathup

**Comment by abcoathup** [comment]
Hi @Akira-Taniguchi,

I didn't realize, but there used to be `Destructible` in OpenZeppelin Contracts but it was removed for the following reason:
>https://github.com/OpenZeppelin/openzeppelin-contracts/pull/1254
`selfdestruct` should be used with tons of care because it's not always safe to use, so it shouldn't be as simple as inheriting a contract.

There was also a recent discussion on reasons not to use `selfdestruct` in the Community Forum:
https://forum.openzeppelin.com/t/what-are-the-best-practices-for-building-selfdestruct-functionality/1508/4?u=abcoathup

I really appreciate you suggesting improvements to OpenZeppelin Contracts, but in this instance based on the above, I will close this Issue.

**Comment by Akira-Taniguchi** [comment]
ok, thanks @abcoathup
