### ISSUE TITLE
WhitelistAdminRole: possible dead-end when removing all admins

### ISSUE THREAD

**Issue by aquiladev** [OpenZeppelin/openzeppelin-contracts#2067]
**📝 Details**

After reviewing `WhitelistAdminRole` contract I found out possible dead-end in the code of the contract.
There is a possibility to remove all admins from the contract, while only admin can add a new admin. If there are no admins, nobody can add new admin and nobody can manage whitelist.

**🔢 Code**
```
contract WhitelistAdminRole is Context {
...
    function addWhitelistAdmin(address account) public onlyWhitelistAdmin {
        _addWhitelistAdmin(account);
    }

    function renounceWhitelistAdmin() public {
        _removeWhitelistAdmin(_msgSender());
    }
...
}
```

**Comment by nventuro** [comment]
Hello @aquiladev! Yes, this is possible for all of our Access Control solutions, even [`Ownable`](https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable) has [`renounceOwnership`](https://docs.openzeppelin.com/contracts/2.x/api/ownership#Ownable-renounceOwnership--), which can be used to achieve the same.

This is considered a feature: many projects find it useful to temporarily have special powers that are later relinquished after a certain condition is met. For the `WhitelistAdminRole`, it may be that you intend to dynamically create a list of whitelisted accounts and then have all admins renounce, so that the list is made final and immutable.

Does this make sense to you? Is there any particular scenario that concerns you where this could lead to an issue?

Thanks!

**Comment by aquiladev** [comment]
Yeah, it makes sense in some cases. In case of dynamic whitelist(eg in my case), it can lead to a dead-end. Due to regulation, I need to restrict the usage of token. the whitelist should be changed when a new customer joins a service.

**Comment by nventuro** [comment]
Yes, that is a common scenario. Is the fact that you could potentially end up with no admins an issue? Arguably, that could also happen due to other reasons, such as losing access to your private keys.

**Comment by aquiladev** [comment]
Yes, it is the same as losing private key. I've got your arguments they are reasonable. I think the issue can be closed.

**Comment by nventuro** [comment]
Thanks for your feedback!
