### ISSUE TITLE
EnumerableSet array push doesn't return an index.

### ISSUE THREAD

**Issue by MicahZoltu** [OpenZeppelin/openzeppelin-contracts#2071]
I think this may be a somewhat recent change to Solidity, but `array.push(x)` doesn't return an index, instead it returns nothing.  This means that https://github.com/OpenZeppelin/openzeppelin-contracts/blob/1e0f07751ea0badce1f51bc23578b5b1ddb4b464/contracts/utils/EnumerableSet.sol#L52 won't work in the latest version of Solidity.

**Comment by nventuro** [comment]
Thanks for pointing this out! Yes, that code will not compile under v0.6.x. `EnumerableSet` was added as part of the v2.5 release, which should be finalized soon (likely tomorrow or next Monday). 

Once that happens, we'll focus entirely on the migration to Solidity v0.6 (#2028), where we'll tackle these issues. Work has already begun on the [dev-v3.0 branch](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/dev-v3.0), though that contract is not part of it yet since those commits where added after the branch was created.

I think we can close this. Thanks again!
