### ISSUE TITLE
utils/String `fromUint256` should probably be `toString`

### ISSUE THREAD

**Issue by Arachnid** [OpenZeppelin/openzeppelin-contracts#2156]
Supposing we use the common convention of using such utility functions as a library:
```
contract Foo {
  using Strings for uint256;

  function test() returns(string memory) {
    uint i = 42;
    return i.fromUint256();
  }
}
```

The function name here tells us nothing - we already knew it was a `uint256` from the variable type. `toString` would be a much more intuitive name, and line up with what other languages use in the same situation.

**Comment by nventuro** [comment]
I think the issue is `Strings` wasn't meant to be used that way, but rather as `Strings.fromUint256()`, so that we could also have `Strings.fromInt256()` and friends. 

Granted the plural form on `Strings` looks strange though, and no other library is used this way - we may want to revise this. Thanks!

**Comment by frangio** [comment]
Both `Strings.toString(x)` and `x.toString()` look nice IMO. And there can be overloads for different types.
