### ISSUE TITLE
AccessControl _grantRole should be internal

### ISSUE THREAD

**Issue by alexroan** [OpenZeppelin/openzeppelin-contracts#2193]
**🧐 Motivation**

To enable dynamic role management at runtime, an admin needs to be granted initially. The public function `grantRole()` requires than the admin role exists and there is already a bearer, so child contracts need to first be able to grant it.

Having `_grantRole()` as private blocks this.

**📝 Details**

Example of a Hierarchical structure using AccessControl here: https://github.com/HQ20/contracts/blob/master/contracts/access/Hierarchy.sol

```
pragma solidity ^0.6.0;
import "@openzeppelin/contracts/access/AccessControl.sol";


/**
 * @title Hierarchy
 * @author Alberto Cuesta Canada
 * @notice Implements a dynamic role structure for Roles
 */
contract Hierarchy is AccessControl {
    event AdminRoleSet(bytes32 roleId, bytes32 adminRoleId);

    /// @dev Add `root` as a member of the root role.
    constructor (address root) public {
        _grantRole(DEFAULT_ADMIN_ROLE, root);
    }

    /// @dev Restricted to members of the role passed as a parameter.
    modifier onlyMember(bytes32 roleId) {
        require(hasRole(roleId, msg.sender), "Restricted to members.");
        _;
    }

    /// @dev Create a new role with the specified admin role.
    function addRole(bytes32 roleId, bytes32 adminRoleId)
        public onlyMember(adminRoleId) {
        _setRoleAdmin(roleId, adminRoleId);
        emit AdminRoleSet(roleId, adminRoleId);
    }
}
```

`_grantRole()` in the constructor doesn't compile. Altering to internal will allow it.

**Comment by nventuro** [comment]
Hello @alexroan, thanks for opening this!

The function you'll want to use in your constructor is called [`_setupRole`](https://docs.openzeppelin.com/contracts/3.x-rc/api/access#AccessControl-_setupRole-bytes32-address-), and it can be used to achieve the result you're looking for. 

It can currently only be called from the constructor, but that limitation is going away in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2195. The reason why I still decided to give it a different name (instead of `_grantRole`) is that I don't want to place that much meaning on a single underscore character: the difference between `_grantRole` and `grantRole `is critical.

Thanks again!
