### ISSUE TITLE
Override ERC721's _isApprovedOrOwner

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#2232]
I have a usecase where ERC721 tokenId are smart contract address:
- The owner of the token is the owner of the contract, and has a priviledge access to it (contract knows the registry address and reads ownership from it).
- The owner of the token can transfer the ownership of the contract using ERC721 logic.

What I'd like to add, is to give the possibility for the contract to perform registry operations on "itself". The most natural way I see to implement that is to overload `_isApprovedOrOwner`:

```
function _isApprovedOrOwner(address spender, uint256 tokenId) internal view override returns (bool) {
    return ERC721._isApprovedOrOwner(spender, tokenId) || spender == address(uint160(tokenid));
}
```

Unfortunatelly, this is not possible since `_isApprovedOrOwner` is not virtual.
- Is there a better way to achieve what I'd like to implement using the existing codebase ?
- Otherwize, would you consider making this function virtual ?

**Comment by nventuro** [comment]
Hello @Amxx, thanks for reporting this!

This is the second valid request we've seen for `virtual view` functions (along with https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2154). We made those non-virtual thinking that a) we could always add `virtual` in the future, and b) it'd likely be hard to write an override without having access to the underlying state variables.

However, in both cases we've seen valid alternatives for overrides, where users either delegate part of the implementation to the base contract (like here), o replace it with new behavior altogether. It's likely that we'll include some form of `virtual view` functions in the next release cycle.

The only thing that worries me slightly about these is that we'll need to carefuly examine the contracts to make sure that these functions are also used internally in all relevant places, instead of state variables being accessed directly. This would require refactoring some contracts (think `ERC20.balanceOf`), and will likely lead to slightly less expensive code due to how the Solidity optimizer works.

**Comment by frangio** [comment]
Closing in favor of #2154. I'll be collecting over there all the functions that have been requested to be made virtual.
