### ISSUE TITLE
Assigning the ownership in the constructor creates issues for factory patterns

### ISSUE THREAD

**Issue by thegostep** [OpenZeppelin/openzeppelin-contracts#2402]
This creates additional 5k deployment cost to update the ownership as a part of the deployment. I recommend using an initializer function which accepts an arbitrary address as the owner.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ec8efd52b4b802042c151e1e7b8be2785ab7cd37/contracts/access/Ownable.sol#L26-L30

**Comment by frangio** [comment]
I agree that using `msg.sender` in the constructor was a mistake. As far as I can tell there is nothing we can do in a backwards compatible way, unless Solidity supports optional arguments at some point.

**Comment by Amxx** [comment]
That is not exactly what you are asking for, but if you plan to have your contract inherit from `Ownable` AND have an initializer, maybe the initializer could use the internal function proposed in #2464

**Comment by thegostep** [comment]
Nice - that's also a much needed improvement but I would still request removing setting ownership in the constructor

**Comment by Amxx** [comment]
Have you considered using OwnableUpgradeable from https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable ?

**Comment by frangio** [comment]
We've come to the following conclusion. We would have slightly preferred to have had the `owner` constructor argument since the beginning, but at this point we don't want to make the breaking change in the existing contracts.

The upcoming storage cost changes in the Berlin hard fork, if I'm reading them correctly, seem to drastically reduce the cost of the extra `SSTORE` caused by having to use an internal setter in the constructor body after the default value of `msg.sender` has already been set.
