### ISSUE TITLE
Merkle tree function (in JavaScript) only allows strings

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2476]
**🧐 Motivation**

Currently, the JavaScript-land function MerkleTree/constructor is expecting that input data will always be provided as variable-length "strings". It then appropriately hashes them to fixed-length Buffers, and processes from there.

By filtering each input this way, it limits the domain of the function and limits interoperability with other systems.

**📝 Details**

You can hash this ["a", "b", "c"].

But you can't hash this [0x817340e.., ...].

**Comment by abcoathup** [comment]
Hi @fulldecent !  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any more code, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by Amxx** [comment]
Hello @fulldecent 

The issue you raise, and the PR that addresses it, looks to only affect `/test/helpers/merkleTree.js`.
This file is not intended to be used outside the tests, and is not package as part of the repo. Furthermore, the new mechanism you add is not used in the tests.

Are you using this helper in your codebase ? If so, it might make more sens to improve it further (better error handling for invalid inputs) and make it part of the `@openzeppelin/test-helpers` repo, and use this improved version in the tests.

**Comment by fulldecent** [comment]
@momannn are we able to share our code here?

**Comment by MoMannn** [comment]
@fulldecent I think we can but your PR already basically solves the problem. Maybe just an example of usage would be beneficial.

**Comment by frangio** [comment]
As @Amxx pointed out, at this moment this issue and PR are updating a function that we use as a test helper only.

On the other hand, this issue is related to the usability of our `MerkleTree` library, which is something we need to make sure is right. But rather than building our own merkle tree function, it would be interesting to instead make sure that a more general purpose merkle tree library can be used together with our Solidity library.

From a quick search I found [miguelmota/merkletreejs](https://github.com/miguelmota/merkletreejs), which in fact seems to have its corresponding Solidity verification library. I think we should instead try to change our tests to use this library, and remove our in-house helper that is not well maintained.
