### ISSUE TITLE
private vs internal and public vs external

### ISSUE THREAD

**Issue by sorleone** [OpenZeppelin/openzeppelin-contracts#2507]
What's the reasoning behind the fact that you always use `private` properties instead of `internal`? By using `internal`, child contracts would be able to use the `internal` variables directly which would offer better control and it would also allow you to turn many `public` functions into `external` ones. This two things combined could offer a bit of a performance boost, due to a lesser number of function calls and to the external keyword.

**Comment by Amxx** [comment]
Having the "internal" variable `private` and not `internal` does prevent child contract from accessing them, which might be bothering in some cases, but also prevents users from writting to them by mistake. It is a security feature, that I understand you might not agree with.

As you may (or may not) have noticed, we made MANY internal function virtual, including the view ones. We believe this should help people overriding some mechanism and customize the contracts to your needs. Again, this might not be enough to you. 

I'd love to have @frangio view on that, and I'm sure he will love to know more about your usecase/

**Comment by frangio** [comment]
Thanks for your suggestion @sorleone.

State variables in OpenZeppelin Contracts are `private` because we want to control the way they are updated. For example, the ERC20 balances mapping should never be updated without also emitting a `Transfer` event. By keeping the mapping private and only exposing internal `_mint`, `_transfer`, and `_burn` functions we can guarantee that the event is properly emitted when the mapping is updated. There are also scenarios where we need to keep certain invariants between the state variables, the example that comes to mind is the many variables in `ERC20Snapshot`, which need to be used carefully in order to keep making sense.

It's true that this results in child contracts having to use internal functions to read variables, which might be slightly more expensive. On this note what I can say is that this extra cost is unlikely to be significant next to the actual cost of reading a variable from storage (which will soon be even more expensive). Additionally, I know the Solidity team is working on inlining optimizations that may erase these function calls from the final contract bytecode.

Regarding `public` vs. `external` I would love to see some examples of functions that would be improved by using `external`. It's been a while since I've compared the cost of the two kinds of functions... From what I recall the main difference used to be whether strings or arrays were copied from calldata to memory, but this is no longer true because `public` functions can now accept `calldata` arrays as arguments.

**Comment by frangio** [comment]
Closing as stale discussion with no actionable item.

**Comment by 5hanth** [comment]
> this is no longer true because `public` functions can now accept `calldata` arrays as arguments.

@frangio is this the reason for still having all OZ [ERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol) contracts with functions such as `transfer()` `transferFrom()` `approve()` `increaseAllowance()` with `public` visibility instead `external` ? curious if its a default preference by EVM now to use `calldata` on cases where the function is not modifying the variable present in the function argument so that changing `public` to `external` is no longer needed for sake of saving gas. 

I see there was another concern why OZ might have not upgraded its contracts replacing `public` with `external`, was it because only from `v.0.5.1` [compiler allows to override](https://github.com/ethereum/solidity/releases/tag/v0.5.1) `public` / `external` in derived contracts and to maintain backward compatibility so this is kept that way?
