### ISSUE TITLE
Missing "override" specifier

### ISSUE THREAD

**Issue by TrinhTrungDung** [OpenZeppelin/openzeppelin-contracts#2514]
Hello guys, I think the functions name(), symbol() and decimals() are missing the "override" specifier. Can anyone verify this one?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f2112be4d8e2b8798f789b948f2a7625b2350fe7/contracts/token/ERC20/ERC20.sol#L59

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f2112be4d8e2b8798f789b948f2a7625b2350fe7/contracts/token/ERC20/ERC20.sol#L67

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f2112be4d8e2b8798f789b948f2a7625b2350fe7/contracts/token/ERC20/ERC20.sol#L84

**Comment by julianmrodri** [comment]
@TrinhTrungDung the `override` specifier is used on derived contracts, in the case when you actually want to replace/modify this functionality. In the case of `ERC20.sol` you are not doing any override, this is meant to be used as a Base class for your Token and this is why these functions are defined as `virtual` because you can override them in your Token contract.
