### ISSUE TITLE
Slither: contract sets array length with a user-controlled value (ERC20Snapshot)

### ISSUE THREAD

**Issue by wschwab** [OpenZeppelin/openzeppelin-contracts#2541]
Hi! Slither turns up an issue with `ERC20Snapshot` that it defines as "high criticality". I wanted to bring it to your attention, even though I assume it's not a problem.

This is the `_updateSnapshot` function ([link](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/ERC20Snapshot.sol#L164)):
```solidity
function _updateSnapshot(Snapshots storage snapshots, uint256 currentValue) private {
        uint256 currentId = _currentSnapshotId.current();
        if (_lastSnapshotId(snapshots.ids) < currentId) {
            snapshots.ids.push(currentId);
            snapshots.values.push(currentValue);
        }
    }
```
about the last line (`snapshots.values.push(currentValue);`) Slither says:
```
ERC20Snapshot (flattened.sol#1731-1878) contract sets array length with a user-controlled value:
        - snapshots.values.push(currentValue) (flattened.sol#1867)
```

I just wanted to bring this to your attention. Thanks for the awesome contracts!

**Comment by frangio** [comment]
Thanks for sharing this! What version of the library was this reported for?

The issue description is weird, because it is not true that the array length is set to a user-controlled value. It is true in some cases that a user can cause the array to grow, but since the array is always pushed to, it can only grow in increments of one. Projects can restrict what users have this power, but even if it is open to anyone, the consequences are very well contained. More details in the [documentation for ERC20Snapshot](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20Snapshot).

**Comment by Amxx** [comment]
Also, this functions pushes value to both `snapshots.ids` and `snapshots.values` ... but the warning is only triggered in the second case.
The only difference I see is that in the first case, the value that is being pushed is produced by the contract itself, while in the second case its a user provided value.

It feels like this warning is more of a "contract sets array **value** with a user-controlled value" ... which I don't see as being an issue.

**Comment by wschwab** [comment]
> What version of the library was this reported for?

`3.4.0`

I was also a bit surprised by the flag, and couldn't figure out how the length would be able to be arbitrarily set by a user-controlled value (other than incrementing by one, which is a feature, not a bug), and figured it was probably just Slither accidentally tripping over something. That being said, I figured I'd at least point it out, ya know, just in case and stuff. Feel free to close if you don't see anything here that needs any further attention.

**Comment by frangio** [comment]
Thanks for reporting!
