### ISSUE TITLE
Deprecate ERC777 implementation

### ISSUE THREAD

**Issue by k06a** [OpenZeppelin/openzeppelin-contracts#2620]
**🧐 Motivation**

There is an opinion that ERC777 is over-engineered and is a bad practice to follow. Moreover it introduces bad abstractions to rely on and requires very important checks to be implemented by every integrator.

Let's switch to EIP2612 (Permit) to deprecate dangerous infinite approve behavior and make it mainstream ASAP: https://github.com/OpenZeppelin/openzeppelin-contracts/contracts/token/ERC20/extensions/draft-ERC20Permit.sol

**📝 Details**

Do we need to collect list of issues? Starting here:

1. Whole idea of avoiding spam tokens by having hook function is wrong. It is not possible to protect from spam tokens because developers of these tokens will always modify their tokens to allow spamming – just ignore them.
2. Token fallback concept is wrong because the callback is being called from token smart contract and there is no way to verify who was the original `msg.sender`. There are so many possible ways to abuse `ERC777Receiver`. The only way to solve it I see – work with whitelisted tokens only – DeFi deserves better approach. Imagine you have DEX and wanna deposit token and do custom action (swap):

    ```solidity
    function tokensReceived(
        address operator,
        address from,
        address to,
        uint256 amount,
        bytes calldata userData,
        bytes calldata operatorData
    ) external override {
        address token = msg.sender;
        balances[token][operator] += amount;
        _performSwap(operator, operatorData); // <- `operator` is not trustworthy, due `msg.sender` can be malicious smart contract
    }

    function _performSwap(address user, bytes memory data) internal {
        // ...
    }
    ```

**Comment by Amxx** [comment]
Hello @k06a,
As a developper working with ERC777 during hackathon, I can only agree that this standard creates a lot of frustration ... and can result in very gas-extensive transactions.

However, deprecating contract breaks backward compatibility. This is not something we would consider doing during a "minor" release. The latest major release was v4.0, less then a month ago. Thus, we wouldn't move with anything like that before a while.

Still, I'd love to build a case for/against ERC777 (and other contract that might not be relevant). This will help us taking decision whenever we fell like moving to the next major version.

**Comment by rstormsf** [comment]
I definitely support this, so new solidity developers won't inherit this broken token design pattern.

**Comment by k06a** [comment]
@Amxx thanks for your support, added 2 cases to the [OP](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2620#issue-843492356).

**Comment by frangio** [comment]
Just to clarify, we can't remove the contract until the next major release, but if there is consensus we can deprecate it, in the sense of not recommending or promoting it anymore, possibly hide it from the documentation site, etc.

Thank you all for raising this.

**Comment by phbdias** [comment]
I agree that there are some issues with ERC777, however I don't see any alternative to avoid the ERC-20 behavior of 'approve' then 'transferFrom' (opposing to the one-step transfer that the ERC777 proposes). There are any safer alternative to ERC777 that I am missing out?

Thanks in advance!

**Comment by k06a** [comment]
@phbdias sure, check out ERC20Permit.sol

**Comment by Amxx** [comment]
@phbdias [ERC1363](https://eips.ethereum.org/EIPS/eip-1363), which is not yet part of OZ contracts, but can easily be added is there is a request for it, is also good to know !

**Comment by frangio** [comment]
We don't think it should be OpenZeppelin Contracts making the decision to deprecate the ERC.

We're happy to include comments in our documentation about the downsides and alternatives.

For actual deprecation, we're happy to host the discussion here, but ultimately we feel that a deprecation requires a more ecosystem-wide agreement.

**Comment by jeffreyscholz** [comment]
@Amxx as rough as the transition is, I think some token that supports a receiver hook needs to be supported. If it isn't ERC777, then by all means ERC1363. Having to approve tokens first is counterintuitive to newcomers and it introduces attack vectors. I don't have strong opinions about the ERC777, but ERC1363 does seem more intuitive to me. Regardless, I'm 100% behind moving to a new token standard away from ERC20. It needs to happen at some point.

**Comment by k06a** [comment]
We can have better EIP which would allow receiver contract to do `transferFrom(msg.sender, …)`, during `transferAndCall` where `msg.sender` will be token contract. But this flow would make it fully compatible with ERC20. Except `msg.sender` will not be beneficiary of the call anymore.

**Comment by k06a** [comment]
Here is the concept of CREATE2-based factory for arbitrary calls, where the receiver of the call still can do `transferFrom(msg.sender, ..., ...)` to have ultimate compatibility with ERC20: https://gist.github.com/k06a/0ea02ecd824bd3d44c760825b62bc264

Pros:
- Smart contract ownership role is not exposed anymore. It uses the factory to have a separate "caller" smart contract for each user.
- The receiver can be ultimately compatible with ERC20

Cons:
- The call receiver should not consider `msg.sender` as beneficiary, we should use methods like `depositFor` and similar. But even if it was used, create2-based proxy factory would allow users to reclaim their ownership.

**Comment by frangio** [comment]
@k06a I was going to mention [ERC827](https://github.com/ethereum/EIPs/issues/827) but I see you were involved in that discussion already!

I think the approach with CREATE2 is interesting but isn't it an important security practice to always invoke `transferFrom` with `msg.sender` as the argument? For example, as seen [here](https://github.com/Uniswap/v2-periphery/blob/2efa12e0f2d808d9b49737927f0e416fafa5af68/contracts/UniswapV2Router01.sol#L70) for Uniswap.

Doesn't this make that approach useless? Because msg.sender would not be the owner of the tokens.

**Comment by k06a** [comment]
@frangio I agree, check my example, it is fully compatible with tranferFrom(msg.sender, …)

**Comment by frangio** [comment]
Oh I hadn't noticed that. It's a pretty interesting idea, but I don't think I'd feel comfortable recommending it. `transferFrom` is not the only thing the receiver may use `msg.sender` for. For example, the auxiliary `Caller` contract may be granted an LP NFT in return, and some of these assets or rights may not be transferable from the auxiliary contract back to the "real" `msg.sender`.

**Comment by k06a** [comment]
@frangio exactly, that’s why I use create2 based factory, where salt is equal to user address. This makes users to own this address of msg.sender in the call 😁

**Comment by Pandapip1** [comment]
Not sure if this issue is still active, but how about https://eips.ethereum.org/EIPS/eip-4524?

**Comment by lukehutch** [comment]
Beyond all the over-engineering, the biggest issue with ERC777 is that it is insecure as defined, because the sender notification interface is called before state is updated: #3463 

@Amxx I agree that ERC1363 is a good standard (simple and secure), as is ERC4524. An implementation of both of these should be in OpenZeppelin, and the two implementations could both share a lot of common code.

Differences: ERC1363 does not allow sending to EOAs or using an EOA as the spender/operator; ERC4524 allows both. ERC1363 allows notification of both spender/operator and recipient; ERC4524 only notifies recipients. Both declare their interface via ERC165.

**Comment by lukehutch** [comment]
> > ERC1363 does not allow sending to EOAs or using an EOA as the spender/operator
> 
> Where do you get that from? AFAIK this is not true.

From [the spec](https://eips.ethereum.org/EIPS/eip-1363) (search for "MUST implement"), and from the reference implementation: [1](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L51) [2](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L131).

Maybe you're thinking of using the ERC20 `approve`/`transferFrom` methods from an ERC1363-capable token, because ERC1363 is a superset of ERC20. I'm referring to the ERC1363-specific methods, `approveAndCall`/`transferFromAndCall`.

> > ERC1363 allows notification of both spender/operator and recipient;
> 
> How is that an issue ?

I wasn't saying it was an issue. I was only pointing out differences between the APIs, to show that there are reasons to implement more than one of these standards or proposals.

One of the primary reasons for the existence of ERC777, ERC1363, ERC4524, etc. is to prevent tokens being sent to contracts that do not know what to do with them, especially non-proxied contracts that cannot be modified (because it causes any received tokens to be lost forever). All of these standards prevent sending to contracts that do not define or declare the right interface. ERC777 and ERC4524 also transparently degrade to a standard transfer when sending to an EOA. ERC1363 doesn't allow that, so it's technically the strongest of all three standards in terms of guaranteeing that you're only sending to the desired address. But being able to send to an EOA using the ERC777 or ERC4524 API, without having to switch back to the ERC20 API, has the benefit of convenience.

Another slightly more esoteric issue with ERC777, by the way, is that if the receiver declares the correct ERC1820 interface but somehow incorrectly defines the receiver notification hook, so that the function signature is wrong, and if that contract defines a fallback function that does not revert, then the ERC777 token contract will think it successfully notified the receiver even though the receiver notification hook never got called. Therefore the fallback function feature of Solidity actually breaks the ERC777 standard, for improperly implemented receivers. ERC1363 and ERC4524 don't have this issue, because they require the hooks they call to return their own function selector as a return value.

**Comment by Amxx** [comment]
> > > ERC1363 does not allow sending to EOAs or using an EOA as the spender/operator
> > 
> > 
> > Where do you get that from? AFAIK this is not true.
> 
> From [the spec](https://eips.ethereum.org/EIPS/eip-1363) (search for "MUST implement"), and from the reference implementation: [1](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L51) [2](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L131).
> 
> Maybe you're thinking of using the ERC20 `approve`/`transferFrom` methods from an ERC1363-capable token, because ERC1363 is a superset of ERC20. I'm referring to the ERC1363-specific methods, `approveAndCall`/`transferFromAndCall`.

It says that
`A **contract** that wants to accept token payments via transferAndCall or transferFromAndCall MUST implement the following interface:`
It also says that 
`This proposal has been inspired by the [ERC-721](https://eips.ethereum.org/EIPS/eip-721) onERC721Received and ERC721TokenReceiver behaviours.`

My understanding is that you should be able to `transferAndCall` (or similar) to an address that has no code ... the call will be successful, and we should accept the empty returndata if the target has no code.

**Comment by lukehutch** [comment]
Yes but look at the reference implementation. It cannot send to EOAs, or allow EOAs to act as spender.

Therefore, it's clear that the total omission of any mention of EOAs in ERC1363 actually originates from the author's intent that "A contract that wants to accept" means "A contract (and only a contract) that wants to accept"...

**Comment by Amxx** [comment]
> One of the primary reasons for the existence of ERC777, ERC1363, ERC4524, etc. is to prevent tokens being sent to contracts that do not know what to do with them

That may be the goal of 4524, but it is not the reason for 777 or 1363. I'm particularly sure of that in the context of 1363. The reason is for the contract to react to a token transfer, which simplifies the "approve + transferFrom" workflow.

**Comment by Amxx** [comment]
> Yes but look at the reference implementation

Do you have a link? Its not in the ERC. (Also the reference implementation could technically be wrong, it does not replace the specs)

**Comment by lukehutch** [comment]
> > One of the primary reasons for the existence of ERC777, ERC1363, ERC4524, etc. is to prevent tokens being sent to contracts that do not know what to do with them
> 
> That may be the goal of 4524, but it is not the reason for 777 or 1363. I'm particularly sure of that in the context of 1363. The reason is for the contract to react to a token transfer, which simplifies the "approve + transferFrom" workflow.

I pointed this out in my comparison of these standards. ERC1363 is the only one that is capable of notifying the spender, and that's quite interesting and unique. But the whole purpose of notifying any party originated from the fact that hundreds of millions of dollars have been lost already because of ERC20 tokens being sent to contracts that couldn't handle them.

> Do you have a link? Its not in the ERC. (Also the reference implementation could technically be wrong, it does not replace the specs)

I provided the link already. Here it is (here they are) again: [1](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L51), [2](https://github.com/vittominacori/erc1363-payable-token/blob/master/contracts/token/ERC1363/ERC1363.sol#L131)

**Comment by lukehutch** [comment]
The specs are simply ambiguous. They do not even address the issue of what happens if an EOA is a recipient or spender.

**Comment by Amxx** [comment]
For the record, we have a PR for adding 1363: #3017

**Comment by Amxx** [comment]
IMO, there is no such thing as the reference implementation unless it's referenced in the ERC in a way that is immutable.

What if the author reads this, and updates the code on its implementation, would that change the (final) standard?

**Comment by lukehutch** [comment]
It's a fair question, but there is principle and then practice. Even if we asked the author if their intent was what was in the reference implementation and they said yes, they can't update a standard once it's final. And since the standard is actually ambiguous in this case (or omits explaining how a critical corner case should work), it gives a lot of latitude for the reference implementation to be accepted as the standard way to resolve the ambiguity.

**Comment by lukehutch** [comment]
I just don't see how digging in on your particular interpretation of ambiguous wording in the spec is better than having OpenZeppelin have the same behavior as the reference implementation written by the same author as the spec. It really is not. If the spec is ambiguous and you choose to resolve the ambiguity in the opposite way from the reference implementation, you're going to create compatibility problems needlessly.

**Comment by Amxx** [comment]
I pinged the author so that he can give is view on the matter.

**Comment by vittominacori** [comment]
@Amxx @lukehutch thanks for the overview on that missing part of the spec. Happy to discuss about it.

When I PR the EIP1363, I did not analyzed the EOA address behavior because of my purpose was to standardize the transfer (or the approve) to a contract capable to be notified and make a callback in a single transaction. So in fact, it says that receiver or spender MUST implement the interface.

I referred the ERC721 behavior (I meant the onERC721Received approach), but ERC721 has a single method both for EOA or contracts. As ERC1363 was built on top of ERC20 I couldn't change the standard ERC20 transfer to add  bytes data and I also didn't want to overload method signatures. So I added the *AndCall methods just to be used with contracts. If we want to transfer to EOA, or to a contract that does nothing, we can use the standard ERC20 transfer.

I didn't included implementation in the EIP because the reviewer said to remove any external link.

**Comment by lukehutch** [comment]
Thanks @vittominacori -- I agree it makes logical sense to just use ERC20 methods for transfer to EOA, therefore ERC1363 implementations should succeed only with compliant recipient or spender implementations. (Standards that break ERC20 backwards compatibility (eg. ERC223) are problematic.)

**Comment by frangio** [comment]
The conversation about EIP 1363 is off topic here. Please continue the discussion in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3017.

**Comment by frangio** [comment]
**Going back to the discussion about ERC777...**

I really wouldn't mind deprecating this contract. It seems pretty clear we've learned that it's not good practice. In particular, the apparent interface-compatibility with ERC20 with subtle differences in behavior, which have extremely important consequences as to reentrancy, was a really bad idea. Even though the ERC20 interface is not required, our implementation includes it by default.

So, I would recommend to deprecate this contract in our next release. If we hear complaints from users for whom ERC777 is important, we can consider adding a version of ERC777 that does not have the ERC20 compatibility layer. However, as far as I know, its advanced features are not in wide use.

cc @k06a @Amxx

**Comment by lukehutch** [comment]
Just removing the ERC20 API from the ERC777 implementation will not fix the reentrancy issue, because the reentrancy issue is introduced by the EIP itself, by specifying that the sender notification hook (if defined) should run before any state is updated.

**Comment by lukehutch** [comment]
The solution is to either break with the standard (calling the sender hook after state is updated) -- which it sounds like nobody is comfortable with doing -- or remove ERC777 entirely. Ideally there would be a warning added to EIP777, but I don't think there's a provision for that.

**Comment by k06a** [comment]
I have no idea why would anyone wish to use ERC777, except newcomers who do not understand what they really need - they think it is “swiss army knife”.

**Comment by lukehutch** [comment]
Is there any way to determine how many contracts have been deployed to Ethereum main net that implement the ERC777 API, or the ERC777 sender or receiver APIs?

**Comment by k06a** [comment]
@lukehutch I’ll try to count both using dune.com

**Comment by lukehutch** [comment]
@k06a Super helpful, thanks for running this.

Can you please also run for the sender callback interface, because that's the one that violates Checks-Effects-Interactions (and sender notification is probably much more rare than receiver notification).

**Comment by k06a** [comment]
> ERC-777 is officially "Not Recommended" (3 weeks ago). It says "ERC-777 is difficult to implement properly, due to its susceptibility to different forms of attack"

https://twitter.com/subinium/status/1577194524341739520
https://ethereum.org/en/developers/docs/standards/tokens/erc-777/

**Comment by lukehutch** [comment]
@k06a thanks for the update, this is the appropriate outcome.

One other point I wanted to mention about ERC1363 and ERC4524: both of them require their notification hook functions to return a magic value (the function selector for the notification hook function), which fixes an issue that ERC777, ERC223, and ERC667 had. The notification hook functions of ERC777, ERC223, and ERC667 did not return a value. Therefore, if the notification hook function was not implemented but a fallback function was implemented, it was possible for the notification hook call to appear to succeed when in fact the call should have ended up failing, because that function was not defined.

Therefore, if anyone is looking for an alternative to ERC777 specifically to prevent token loss by sending to contracts that do not support receiving tokens, please consider adding ERC1363 and ERC4524 to your ERC20 implementation. (They are both similar enough that both can be implemented with very little code.)

**Comment by frangio** [comment]
We should move forward with deprecation.

**Comment by Pandapip1** [comment]
As an EIP editor, I can confirm that EIP-777 is not officially deprecated.

As a developer, I can confirm that EIP-777 should no longer be used, and it would be good if OZ hid it from the documentation :)

**Comment by DevABDee** [comment]
Great Discussion. I just wanted to share a [Twitter thread](https://twitter.com/dmihal/status/1251505373992845317?s=20&t=ziq0zxkVf9IedUodKgRT3w), a good counter to this issue. 

The Thread:
https://twitter.com/dmihal/status/1251505373992845317?s=20&t=ziq0zxkVf9IedUodKgRT3w

**Comment by frangio** [comment]
The thread shows the `tokensReceived` hook, which is indeed analogous to ETH transfers and equivalent to ERC721 and ERC1155 "onReceived" hooks, and as pointed out it can be easily dealt with. The issue that is not mentioned in the thread is the `tokensToSend` hook, which can more easily lead to inadvertent checks-effects-interactions violations and reentrancy issues, especially in combination with `tokensReceived`.

**Comment by Amxx** [comment]
Also the `tokensReceived` would be great if it did not require ERC1822 registration ...

ERC777 is not as simple as 721 and 1155 were you "just" implement the hook.

**Comment by epowell101** [comment]
Asking for a quick pointer - if not erc777 (and I'm convinced) then how could we:
- have a erc20 token or similar w/ governance & delegation capabilities
- that we could blacklist addresses 

Why?  The OpenData Community is starting to curate lists of Sybils (yes imperfect).  Nonetheless, the thinking is of a way to prevent known Sybils from gaining access to Sybil lists via the use of our governance token as a future use of the governance token will be to stake or otherwise use it to access updated Sybil lists.

**Comment by Pandapip1** [comment]
The ERC-20 standard (and even the OZ implementation) is more than capable of doing both of the things you want:

* https://docs.openzeppelin.com/contracts/4.x/governance#erc20votes_erc20votescomp
* https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#ERC20-_beforeTokenTransfer-address-address-uint256- (using it to revert if an address is on the blacklist)

**Comment by k06a** [comment]
@epowell101 I agree with @Pandapip1, existing ERC20 extensions are great way to extend functionality of ERC20 tokens.

I also would recommend taking a look at new Token Plugin ERC20 extension. It allows users to participate in on-chain plugins, which can handle delegations, votes, incentives and any other functionalities: https://github.com/1inch/token-plugins. We are also aiming to push this ERC20Plugins extension into OZ library in coming future.

**Comment by freefilm010** [comment]
wouldn't that be 1820? sorry to jump in. I'm learning and what you all do
is nit easy at all..

erc 20 is token standard as is 721...

777 goes backwards with the erc20 and fixes the double approval issue into
one single action. technically better than erc 20... oh yeah it can pay out
to two transactions with one action. thus fir commission and such its paid
same time and also doest get stuck like erc20... I probably sound like an
idiot but I know I am close..

I was reading through all the different final token types. so many awesome
ones like the token backed by hard assets. then there is royalty assets.


long story short I am working on a global project  ND have also filed for
grants, and will be fundraising, crowdfunding, for this global
collaboration. interestingly open zeppelin falls inline with my preferred
selection to contract all the services of issuing contracts, monitoring,
backtesting, auditing, security, to all relating to mining and minting for
the project. also a research amd development fund to collaborate with a few
special groups to see if we can create a newer ecosystem. blockchain
development from start to living adaptable concept...

I like and need to break down every token type to stretch what is and is
not feasible
.. when applied to a proprietary model that I can present to the group once
proper docs are signed by all parties. I feel there is a special element to
be added and timing is critical as the first to market usually is top
product.

I plan to reach out to HQ in NYC on the coming days. like to speak with a
contracting specialist, project manager, lead blochchain developer.

if some one could point me to a well rounded individual that can help
establish the requirements and services into a quotable schedule of prices,
swiftly as I have a collaboration of about 10 entities (should have half
that when completed), 7 contents, and very complicated corporate structure
to keep all parties humble.

d.rey
202.830.5331

**Comment by DaveAppleton** [comment]
> That may be the goal of 4524, but it is not the reason for 777 or 1363

Stopping tokens from getting trapped in contracts was exactly one of the reasons that ERC777 was adopted - at the time it was presented as a far better thought out standard than the ERC223 which even had bugs in the reference implementation.

**Comment by Pandapip1** [comment]
FWIW ERC-223 now exists and is Final. I personally prefer ERC-1363 since ERC-223 breaks applications that expect an `approve` -> `transferFrom` flow, and because ERC-1363 follows a pattern that is more similar to ERC-721/ERC-1155. ERC-223 is slightly more secure, though.

**Comment by lukehutch** [comment]
@Pandapip1 As it is defined in the spec, ERC-223 is not even fully backwards-compatible with ERC-20 (or is not a superset of ERC-20) -- they forgot to include one or two of the ERC-20 functions in the API (I forget which ones).

**Comment by Pandapip1** [comment]
It wasn't a 'forgot', it was a deliberate design choice not to be compatible. I never claimed that ERC-223 was compatible with ERC-20. In fact, I noted that it wasn't:

> ERC-223 breaks applications that expect an `approve` -> `transferFrom` flow

ERC-777 is also incompatible with ERC-20. ERC-223 or ERC-1363 + ERC-20 are both generally better than ERC-777.

**Comment by lukehutch** [comment]
> It wasn't a 'forgot', it was a deliberate design choice not to be compatible.

I don't think that's true at all that they didn't forget to add all the ERC20 functions. You can in fact add ERC-223 over the top of ERC20 if you add one or two missing functions, *and it does in fact work for both standards if you do that.* As somebody who went over the specs with a fine-toothed comb, and created an extremely meticulous rendition of ERC-20, ERC-223, ERC-677, ERC-777, ERC-1363, and ERC-4524 *in a single contract*, I can tell you that ERC-223 was supposed to be a proper superset of ERC-20. But they missed the mark. The reference implementation didn't even match the ERC-223 spec (and was buggy), the spec left out important details, the spec accidentally dropped these one or two ERC-20 functions without reason or justification (I'm not motivated enough to go back and figure out which ones), and more. ERC-223 is a very amateurish "spec", as far as token ERCs go. I strongly recommend against using it.

**Comment by Pandapip1** [comment]
@Dexaran, the author of the spec, has spoken and said that it was in fact a deliberate design choice. It's a design decision I don't really like, but that doesn't change the fact that the removal was intentional. It's also not entirely without merit, even though it can and likely will break things.

I didn't say you couldn't implement everything at once. I didn't say the ERC-223 spec was particularly well-written. I do prefer ERC-1363 over ERC-223. But none of this changes the fact that:

1. Both are valid standards; and
2. They each have their own tradeoffs

It's up to the OZ maintainers to decide which one to use.

**Comment by k06a** [comment]
ERC223+

@Pandapip1 as far as I can remember ERC20 extensions authors criticized ERC20 for a few reasons:
1. Unavoidability of two separate transactions from EOA for `approve` and `transferFrom` tokens.
2. Ability to send tokens to non-validated receiver, which cause millions loss to Ethereum users (see motivation section of ERC223)

So ERC223 by @Dexaran was probably the very first recognizable attempt to improve ERC20: [ERC223 token standard · Issue #223 · ethereum/EIPs](https://github.com/ethereum/EIPs/issues/223)

In Jan 2018 @AugustoL introduced ERC827 which improved ERC223 by adding notification calls to all ERC20 functions (approve/transfer/transferFrom) and making such calls indirect via proxy contract: https://github.com/ethereum/EIPs/issues/827

In April 2018 I came up to a solution on how to maintain compatibility with `msg.sender` “spender” argument of `transferFrom` call. ERC1003 allowed to reinterpret `msg.spender` on the flight as previous token interactor: https://github.com/ethereum/EIPs/issues/1003

At the end of April 2018 I came up with feeless (gasless) abstraction to resolve 2-transaction issue: https://github.com/ethereum/EIPs/issues/1035. By the way GSN (Gas station Network) was proposed much later in December 2018 - https://github.com/ethereum/EIPs/pull/1613

In April 2020 I came up to solution how to resolve beneficiaries collision of misused token or proxy contract address as `msg.sender` inside protocol smart contract. ERC2608 was not properly descibed, but was implemented as CREATE2 factory of proxies per token holder: https://github.com/k06a/ERC2608/blob/master/contracts/ERC2608.sol - it allowed users to reclaim mistakenly lost assets and values from own proxy.

After few years of experience in the DeFi and multiple discussions I still feel that problems of this approach are not resolved and implementations are a bit tricky. I believe ERC2612 (Permit) resolves issue of 2-transactions with EIP712 abstractions in a much better way - clean and scalable solution for replacing transactions/calls with indirect signed actions and merging their execution into single transaction.

Nowadays I would consider whole ERC223-like approach as anti-pattern of smart contract engineering. Moreover I believe including this such functionality in the core part or ERC721 was a mistake. Maybe we can redefine extracted core logic of ERC721 into new ERC****, which will be iconic minimalistic NFT ERC.

**Comment by k06a** [comment]
@Pandapip1 I would say they surely exist in the form of discussions, but not properly submitted to the repo.

**Comment by Pandapip1** [comment]
They are discussions. They are not official standards and therefore generally shouldn't be used. Anyone can submit them to the repo, right now, and start the process of turning them into actual EIPs.

**Comment by Dexaran** [comment]
@lukehutch 

>As it is defined in the spec, ERC-223 is not even fully backwards-compatible with ERC-20

>I don't think that's true at all that they didn't forget to add all the ERC20 functions.

ERC-223 was designed to be a security patch to insecure ERC-20 standard. I repeat, it was not intended to be a superset or an extension of ERC-20, it was designed to be a **SECURITY PATCH**. Here it is written 
  https://github.com/ethereum/EIPs/pull/610#issuecomment-296711733

There are two main security problems with ERC-20.

### Problem 1: placing a burden of making security decisions on a user combined with lack of error handling for erroneous users decisions

There are two methods of transferring ERC-20 tokens: (1) transfer, (2) approve & transferFrom. One is designed to be used for transfers to EOAs another is designed to be used to transfer tokens to smart-contracts. ERC-20 token contract however does not determine the method automatically and enables users to determine it themselves.

If a user will pick a wrong method - the users money gets burned even though it is known for sure that this was a mistake. As of today, at least $201M worth of ERC-20 tokens were lost in this way.

- For example this accident: https://www.reddit.com/r/0xProject/comments/7lpc5n/ive_sent_my_tokens_to_the_zrx_smart_contract/

- And this accident: https://beincrypto.com/1-million-usdt-nearly-lost-to-simple-user-error/

- And this accident: https://www.reddit.com/r/ethereum/comments/16bqvj8/4_hours_ago_240k_worth_of_cro_were_deposited_to/

### Problem 2: approve & transferFrom is a pull transacting method which was not designed for trustless systems

Here is my detailed article that describes why it is a very bad idea to use pull txs in tokens: https://medium.com/@dexaran820/erc-20-approve-transferfrom-asset-transfer-method-poses-a-threat-to-users-funds-safety-ff7195127018

TL;DR it opens up a wide range of attacks like permit scams or over-authorizing contracts to manipulate users tokens.

There is even more money lost to pull transacting flaws. 

- For example this accident: https://twitter.com/realScamSniffer/status/1686761980365832197

- And this accident: https://twitter.com/realScamSniffer/status/1710423552380502331

- And this accident: https://twitter.com/feindura/status/1676623784726470658

It is known that approvals are (1) totally unnecessary if you have 'transaction handling' implemented, (2) gas inefficient and (3) risky for users.

Here is my comment regarding approvals: https://github.com/ethereum/EIPs/issues/20#issuecomment-289227754


### Why ERC-223 is designed as it is

@Pandapip1 

>@Dexaran, the author of the spec, has spoken and said that it was in fact a deliberate design choice.


If ERC-20 has two problems (placing a burden of making a security decision on a user and pull transacting method) the main goal of ERC-20 was to replace these. The "user-made choices" must be removed - thats why `transfer` function of ERC-223 automatically determines which transferring method to execute on transfer. Approve & transferFrom are also removed. If someone wants to introduce this functions in their ERC-223 token implementation they can do it but it is not obligatory by the standard because ERC-223 supports transaction handling.

It must be noted that EOS C++ native token is purely based on ERC-223 transferring logic and it works perfectly. Also ERC-721 transferring logic is based on ERC-223 logic and it also works without problems (and there is a reference to ERC-223 in the initial ERC-721 documentation).

Here is a comparison of token standards and transferring methods they support:

| Transaction type  | [ERC-223](https://eips.ethereum.org/EIPS/eip-223)   |  Ether    | [ERC-20](https://eips.ethereum.org/EIPS/eip-20)             | [ERC-721 (NFT)](https://eips.ethereum.org/EIPS/eip-721) | [ERC-777](https://eips.ethereum.org/EIPS/eip-777) | [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) | [ERC-1363](https://eips.ethereum.org/EIPS/eip-1363) | [EOS C++ token](https://github.com/EOSIO/eosio.contracts/blob/master/contracts/eosio.token/src/eosio.token.cpp) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Push tx       | +             | +             | - | + | + | + | + | + |
| Pull tx   (risky)    | -             | -             | + | + | + | + | + | - |
| Unhandled  (insecure)   | -             | -             | + | - | + | - | + | - |


@lukehutch 

>the spec accidentally dropped these one or two ERC-20 functions without reason or justification

For security reasons. ERC-223 is prioritizing security over backwards compatibility. Any standard that implements `transfer` function compatible with ERC-20 standard inherits all the security problems and therefore will cause the same financial losses to end users. Quite good reasons to avoid this I think.

>ERC-223 is a very amateurish "spec", as far as token ERCs go. I strongly recommend against using it.

If you recommend using specs that are straight up insecure and cause financial losses to users - this is your right. But I recommend prioritizing security in financial systems.

**Comment by Dexaran** [comment]
@k06a 

>Nowadays I would consider whole ERC223-like approach as anti-pattern of smart contract engineering.

Only on Ethereum, only among solidity devs for some reason.

Newer platforms like EOS utilize ERC-223 patterns without problems. And plain ether transfers work as ERC-223. It would be quite logical for developers to implement tokens that work in a similar way as ether (since they anyways need to know how ether transfers work) without developing a whole new transacting method that introduces two security problems.

Not even going deeper into discussing if 200 million dollars lost over 4 years are enough to start thinking that it is a problem.

**Comment by k06a** [comment]
Thanks for the interesting insights @Dexaran. But don’t you think that Ethereum smart contract engineering has the most evolved community and approaches in this industry?

I believe there are a lot of newer blockchains but the most protocol tech innovations happens on Ethereum and Ethereum-like chains, but  rarely on non Ethereum-like chains. And OpenZeppelin smart contract library is probably one of the most advanced in industry in terms of wide-spreading the patterns and approaches? That fact that ERC223 and ERC827 were excluded from the library means that approach did not passed natural selection during protocol tech evolution.

**Comment by Dexaran** [comment]
@k06a 

>Don’t you think that Ethereum smart contract engineering has the most evolved community and approaches in this industry?

Depends on which industry to benchmark against. 

If we compare Ethereum development community to the global programming community - Ethereum is by far not well-developed. We are lacking such basic things as "error handling" in its token standards and "a process to modify final EIPs upon vulnerability disclosures": https://github.com/ethereum-cat-herders/EIPIP/issues/255#issuecomment-1671895165

Like... nobody ever expected that there can be a security vulnerability disclosed AFTER an EIP gets final status? For some reason Dexaran needs to be the first guy to raise this issue and tell the whole Ethereum community that such things can happen https://github.com/ethereum-cat-herders/EIPIP/issues/257#issuecomment-1693740271

**This is a clear sign that this development community is not well-developed** if such basic well-known widely adopted things are not a standard there. If we compare to wider programming community. If we compare Ethereum community to [Callisto community](https://callisto.network/) however, Ethereum one can be considered more developed.


>I believe there are a lot of newer blockchains but the most protocol tech innovations happens on Ethereum and Ethereum-like chains

Ethereum is a smart-contract platform with the highest network effect. It doesn't automatically mean it is the most technologically advanced one. Similarly Bitcoin is the highest cap crypto today but it doesn't mean it's the most technologically advanced.

Speaking of numbers the performance of EOS VM (WASM) probably 500x higher than EVM https://arxiv.org/pdf/2012.01032.pdf

And EOS has a number of security advantages over Ethereum as well https://www.eosgo.io/blog/shadowed-advantage-of-eos-that-you-might-not-know/

>And OpenZeppelin smart contract library is probably one of the most advanced in industry in terms of wide-spreading the patterns and approaches?

May be it's the most advanced in terms of wide-spreading but definitely not in security. The title says the contracts are "secure" but the implementation causes end users to lose money. Personally I wouldn't call something that caused 200 million dollars loss a "secure software".

![OZ_not_so_secure_contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/26142412/8452a969-41b5-48bf-af45-92bb563563db)

What is even worse they refuse to fix it https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4451 and they don't even update the documentation to add an important security warning so yeah, I'm quite unhappy about OpenZeppelins approach.

They are definitely doing good job providing a lot of code examples.

They are doing bad job not making these code examples secure and refusing to describe caveats that caused millions of dollars losses.

>That fact that ERC223 and ERC827 were excluded from the library means that approach did not passed natural selection during protocol tech evolution.

I wrote a sophisticated description of what has gone wrong here https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3736#issuecomment-1648404823


Also Ethereum's processes (EIPs and related stuff) are not properly designed to coordinate ecosystem upgrades. As the result the first adopted standard can stay "the main one" for ages even if it has such critical problems as security flaws. Have you ever seen any standard superseding an existing one on Ethereum? Personally I've never seen that. Community tends to stagnate and the current processes are not designed to allow for a healthy upgrade.

**Comment by u59149403** [comment]
I think native tokens (EIP-7809) is superior alternative to ERC-20. See my arguments here: https://ethereum-magicians.org/t/eip-7809-native-tokens/21615/9?u=u59149403
