### ISSUE TITLE
Issue with a crowdsale contract

### ISSUE THREAD

**Issue by ValoisProtocol** [OpenZeppelin/openzeppelin-contracts#2637]
Hi, I an experiencing an issue with a crowdsale contract. The crowdsale has been deployed and the withdraw function when called returns the following error Fail with error 'safeERC20': low-level call failed.I am aware this error returns when the Contract address has no tokens but in this situation the Contract has tokens in it. Below is the Contract code and the crowdsale contract itself that produces this error. The participants have deposited bnb however no tokens was returned to them instead when they recieve that error above. 

<https://bscscan.com/address/0xa228fb40bc32b555ef6af1b5ab62f89b48381864#writeContract

**💻 Environment**

Remix compiler 0.8.3 

Is there an issue in the Contract or deployment? If so how to rectify it. Cheers

**Comment by frangio** [comment]
There may be something wrong with your contract code. I don't have enough data to debug what is happening. It does sound like there may not be enough balance of the token. You will need to try to debug the function call to exactly what is failing.

**Comment by frangio** [comment]
We don't have enough bandwidth right now to guide you through debugging the code. Let us know if you get more information and we can try to help based on that.

**Comment by ValoisProtocol** [comment]
Hi Frangio. We still couldn't identify the issue 
. All the steps seem to be have done correctly. Can you please check 

If you see the link above, the tokens native to the project are in there. The only issue is that when people come to withdraw, they get that error.

**Comment by Amxx** [comment]
@ValoisProtocol 
Here is my understanding of your issue:

- The balance of the sale contract `0xa228fB40bc32B555eF6AF1b5aB62f89b48381864` on the token `0xeb27c43BE8b0a1DD0377F2c66b4f6353290c0F27` is currently `150000000000000`
- In this transaction, a user https://bscscan.com/tx/0x2369b7c68f046ce2eb7b2273c6e533741a0340ce27ee20c80e6526aa17a9ca9c a user bought an amount of `7560000000000000000000`.

Even if you just plan to deliver 10%, 7560000000000000000000*10% is way more then the sales contract balance. An address cannot transfer more then the balance, so the transfer reverts.

There is nothing wrong with the contract (that I can spot) The problem is either that you allowed sale to sell too many tokens, or that you did not give enough tokens to sale in the first place.

FYI, total token sold are `1321041998134693812600000` so one would expect the balance to the sale contract to at least match that

**Comment by ValoisProtocol** [comment]
Thank you, this issue was in the decimals for rate. Uint was 18 decimals. And so this was causing the error. Thank you
