### ISSUE TITLE
Add `reset` function to `Counters` library

### ISSUE THREAD

**Issue by Xu-Tian** [OpenZeppelin/openzeppelin-contracts#2677]
**🧐 Motivation**

In a scenario like moving a point in one direction in a bounded segment, a counter can reach the upper limit and then needs to get reset to start all over again. It would be great if a reset function can be added to the Counters library.

**📝 Details**

```
function reset(Counter storage counter) internal {
    counter._value = 0;
}
```

**Comment by Amxx** [comment]
Hello issue @Xu-Tian , and tank for your issue.
This sounds like a reasonable request that is easy to implement!

**Comment by Xu-Tian** [comment]
You are welcome.

I noticed `unchecked` is added in the new function, and I also noticed `unchecked` is added to `increment` and `decrement` as well. I'm wondering why this is needed. By default, the values are checked and will throw when overflow or underflow. Is that the right feature to have?

```
 function reset(Counter storage counter) internal {   
            unchecked {
                counter._value = 0;
            }
}
```

**Comment by Amxx** [comment]
`uncheck` removed solidity 0.8.0 built-in safe to save some gas. It is in the counter library, because the checks are not needed:
- for increment to overflow, you would need to call it 2**256 times, which is not realistic in this universe
- decrement is already protected for overflow thanks to the `require()` that will raise an error string.

In reset, assigning 0 doesn't include safemath protection, so unchecked is not needed (and won't do anything good or bad)

**Comment by Xu-Tian** [comment]
Got it. I did a test and it is indeed using less gas. Thanks for the clarification.
