### ISSUE TITLE
Include supported Node.js versions in test suite and allow them to fail

### ISSUE THREAD

**Issue by fulldecent** [OpenZeppelin/openzeppelin-contracts#2770]
**🧐 Motivation**

Currently OpenZeppelin Contracts only builds with Node.js version 12, and that version is [not under active development by vendor](https://nodejs.org/en/about/releases/).

**📝 Details**

- [ ] Set a policy that OpenZeppelin Contracts is supported on Node.js 12 and that support for "ACTIVE" and "CURRENT" versions of Node.js is desired (i.e. pull requests welcome)
   - [ ] Announce this policy on main README, DOCUMENTATION or other authoritative place
- [ ] Update GitHub Actions build script to implement a matrix build strategy
- [ ] Mark versions other than version 12 as `continue-on-error`

An example of this matrix strategy and `continue-on-error` is implemented at https://github.com/bovigo/vfsStream/blob/d66bb85a6738288a833955c36586f2eb4a176cf5/.github/workflows/runTests.yml

**Comment by frangio** [comment]
OpenZeppelin Contracts does not have dependencies and is a pure Solidity package, so it works with any Node.js version. For this reason I don't see the need to add this additional configuration on GitHub Actions, which will just add CI time and slow the contribution process unnecessarily.

For development, the repository builds fine on Node.js 12, 14, and 16, all the currently supported versions, because we keep our dependencies up to date. So I'm not sure what you mean by "only builds with Node.js version 12". Can you clarify?

**Comment by frangio** [comment]
Maybe you meant that dependencies don't support Node 10? I think this was introduced a few months by one of our dev dependencies. I've just downgraded it to support Node 10 because even though it is already End-of-Life, I'd like to support Node 10  if possible.

However, developers should note that this won't last long. Since Node 10 has been End-of-Life for several months now, packages have slowly started to drop support for it.

**Comment by frangio** [comment]
Will close this issue since we don't intend to add a Node version matrix to CI for the reasons explained above. We expect that running CI on the oldest supported Node version (12 at the moment), plus keeping dependencies up to date, and maintainers using recent Node versions locally, should all be enough to guarantee that things work smoothly for people. Feel free to continue the conversation.

**Comment by fulldecent** [comment]
When you say "I'd like to support Node 10 if possible" you are referring to having the build work (dev dependencies) for Node 10.

The test cases here are arguably more valuable here than the Solidity code. And test cases and code are indeed both part of the "package" here and in other software projects.

Adding Node 10, 14, ... to a build matrix will NOT slow down build times because they run in parallel. (They will add billable minutes to your GitHub account, if that is worth discussing.)

You say "I'd like to support Node 10 if possible", which I agree is a good idea. I think the best way to get that is to put it in the matrix. Then contributors will know that you would like Node 10 support rather than having to search through the issues to learn this obscure fact from your-and-my conversation. In this way you will speed up the contribution process.

---

Then when you no longer want to support Node 10, because it is not possible... you accept a one-line change. And everybody that is interested in this will see the change in the expected place.

---

By "supporting" builds in 10, 14, ... and putting them in the matrix, everybody will see the warnings which apply only to some versions. Somebody should go fix each of these warnings. And by putting 14 in the matrix now (as a can-fail) you highlight some issues that other people can fix now (whether here or upstream). By the time OZC switches to a new Node version perhaps it will build without warnings from the get-go.
