### ISSUE TITLE
ERC20 - use `internal` visibility rather than `private` for stored variables

### ISSUE THREAD

**Issue by Ro5s** [OpenZeppelin/openzeppelin-contracts#2807]
for dev flexibility, we might use `internal` visibility rather than `private` for `_balances`, `_allowances`, `_totalSupply`, `_name` & `_symbol` to allow option of referencing them through inheritance:

![image](https://user-images.githubusercontent.com/41117279/127905694-c20edef9-e4f9-415f-b84e-66b37779659c.png)

**Comment by frangio** [comment]
Thanks for the suggestion @Ro5s. We use private variables so that we can have tighter control in the way that the values are modified. For example, we can guarantee that balances and total supply in ERC20 are modified together, and that this modification emits an event. This is not something we're willing to change currently.

To access these values you should be able to use the functions of the contract. To customize these values you can generally use inheritance and overriding.
