### ISSUE TITLE
Make ifAdmin modifier virtual

### ISSUE THREAD

**Issue by pertsev** [OpenZeppelin/openzeppelin-contracts#2808]
**🧐 Motivation**
In the current implementation, it's not possible to change ifAdmin behavior so we stuck with one specific admin that has to call the proxy, which is not good.

**📝 Details**
This tiny upgrade would allow `ifAdmin` modifier overriding to change its logic.

**Examples**
1. In my specific case, I would like to have an upgradeable contract on Optimism L2 with an admin on L1. So the `ifAdmin` looks like the following:
```js
modifier ifAdmin() override {
  if (msg.sender == address(messenger) && messenger.xDomainMessageSender() == _admin()) {
    _;
  } else {
    _fallback();
  }
}
```
full example [here](https://github.com/tornadocash/tornado-pool/blob/optimism/contracts/CrossChainUpgradeableProxy.sol#L30-L36)

2. The proxy can have several admins that are not EOA but contracts. In this case ifAdmin checks `msg.sender` against array of addresses.

**Comment by Amxx** [comment]
Hello, 

Usually, I would argue that the modifier should not be virtual, and that instead it is msg.sender that should be replaced with `_msgSender()` from `Context` which could be overridden.

However, `Context` is not part of `TransparentUpgradeableProxy`. Making Context part of it would be dangerous if it is overloaded with an implementation that uses some storage (only immutable variable would be safe).

@frangio, any opinion ?

**Comment by pertsev** [comment]
@Amxx should we mention some else to make it happen?
@frangio any thoughts?

**Comment by frangio** [comment]
Sorry, I just saw this.

I would recommend implementing this with a custom `ProxyAdmin` contract, rather than a custom proxy. I think it is safer to keep the proxy exactly like it is and has been tried and tested, rather than customizing it. The recommended deployment for a Transparent proxy is to set a `ProxyAdmin` instance as the admin, and the `ProxyAdmin` can be made Optimism-aware quite easily.

A sketch (will not compile without some changes):

```solidity
contract OptimismContext is Context {
    function _msgSender() override returns (address) {
        if (msg.sender == address(messenger)) {
            return messenger.xDomainMessageSender();
        }
    }
}

contract OptimismProxyAdmin is ProxyAdmin, OptimismContext {
   // overrides 
}
```

As for making this modifier virtual, unless a really good use case comes up, I would prefer to keep it non-virtual, because I don't think we'd support customizations of this contract.
