### ISSUE TITLE
Make IERC20 support decimals (from ERC20)

### ISSUE THREAD

**Issue by JackBekket** [OpenZeppelin/openzeppelin-contracts#2826]
**🧐 Motivation**
My contracts work with ERC20 stablecoin contracts as a currencies, and sometime I need to make a conversion say USDT to USDC
In this case I need to work with decimals from contracts while I do convertaion, so I need to get decimals from those contracts, and I would like to do that by IERC20 interface.

**📝 Details**
Make IERC20 (interface) support of ```decimals()```, to get ability to get decimals from erc20 token contracts, using only their interface IERC20 contract

**Comment by julianmrodri** [comment]
I think they are already providing this using the `ERC20Metadata` extension. You can use that interface in your contracts if you are sure the tokens you manage/will manage expose this information.

Check [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/IERC20Metadata.sol) if this works for you.

**Comment by Amxx** [comment]
Hello @JackBekket,

If you have a look at the [ERC20 specifications](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md), you'll see that `name`, `symbol` and `decimals` are optional. Consequently, they are NOT part of IER20, because a contract that would not implement them would still be compliant with the standard.

If you want to have the "extended" interface, with these optional functions, you can (as @julianmrodri pointed out) use the `IERC20Metadata` interface. [This is what we do in @openzeppelin/subgraph for example](https://github.com/OpenZeppelin/openzeppelin-subgraphs/blob/main/src/datasources/erc20.yaml#L16).

Note that when reading any of these three functions, you should make sure you have a fallback mechanism if the function is not implemented and the call reverts.
