### ISSUE TITLE
@openzeppelin/contracts/proxy/UpgradeableProxy.sol not found for solidity 0.8.7

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [OpenZeppelin/openzeppelin-contracts#2888]
I am studying the factory patron on the blog
https://blog.openzeppelin.com/workshop-recap-cheap-contract-deployment-through-clones/
I am trying to reproduce the example and I get that 
@openzeppelin/contracts/proxy/UpgradeableProxy.sol is not found

I also look at the documentation that that is where the file should be:

https://docs.openzeppelin.com/contracts/3.x/api/proxy#UpgradeableProxy

**💻 Environment**

**📝 Details**

**🔢 Code to reproduce bug**

import "@openzeppelin/contracts/proxy/UpgradeableProxy.sol";

 env:
Truffle v5.4.10 (core: 5.4.10)
Solidity - 0.8.7 (solc-js)
Node v16.9.1
Web3.js v1.5.2

**Comment by Amxx** [comment]
Hello @israel-gonzalezmedina 

The documentation you are pointing to is for an old version of this library. [You should check documentation for 4.x](https://docs.openzeppelin.com/contracts/4.x/api/proxy#ERC1967Proxy).

Also, since 4.0, `proxy/UpgradeableProxy.sol` moved to `proxy/ERC1967/ERC1967Proxy.sol`

The [example repository](https://github.com/OpenZeppelin/workshops/tree/master/02-contracts-clone) that is linked from the blog recap is using `@openzeppelin/contracts@3.4.0` because we needed 0.6.x support for the uniswap example.
