### ISSUE TITLE
redundant Proxy1967 construction-time check

### ISSUE THREAD

**Issue by drortirosh** [OpenZeppelin/openzeppelin-contracts#2907]
In ERC1967Proxy there is:

```solidity
    bytes32 internal constant _IMPLEMENTATION_SLOT = 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc;
```

and then

```solidity
    constructor(address _logic, bytes memory _data) payable {
        assert(_IMPLEMENTATION_SLOT == bytes32(uint256(keccak256("eip1967.proxy.implementation")) - 1));
        _upgradeToAndCall(_logic, _data, false);
    }
```

With solidity 0.8, I think this check is redundant now, as constant keccak can be used at compile-time.

So instead, the constant should be defined as:

```solidity
    bytes32 internal constant _IMPLEMENTATION_SLOT = keccak256("eip1967.proxy.implementation");
```

and require no run-time check (even if only at construction time, it adds to constructor size and takes gas..)

**Comment by frangio** [comment]
Following up on the suggestion to use an immutable variable. I implemented it in [this branch](https://github.com/frangio/openzeppelin-contracts/tree/1967-immutable) but it's a breaking change of the required Solidity version from 0.8.0 to 0.8.9, and anyway it's not a real improvement because the hash is still calculated in construction time.

We should push the Solidity team to do more compile-time constant evaluation.
