### ISSUE TITLE
Possible error in ECDSA.sol

### ISSUE THREAD

**Issue by grapevinegizmos** [OpenZeppelin/openzeppelin-contracts#2914]
It appears that ECDSA.recover returns incorrect address for a signature created on the client side by ethers.SignerWithAddress.signMessage.

**💻 Environment**

Solidity 8.4
ethers.js version 5.4.7
Hardhat version 2.6.5
Running in VS Code locally with MetaMask 10.2.2

**📝 Details**

I am attempting to use ECDSA.recover to confirm that that a document string supplied to contract in a function call was in fact signed by the account of msg.sender.  I have been unable to find any error in the code below but perhaps I misusing the libraries somehow.

It may the problem is that the signature produced by `ethers.SignerWithAddress.signMessage(msg)` isn't the kind of signature ECDSA is meant to work with, but I couldn't tell from the documentation.  

I noted that the actual signature produced is a string 132 characters in length, but ECDSA.recover expects a signature of 65 bytes.  I noticed that apply `abi.encodePacked` to the signature reduces it length from 132 to 65, so I assume that is what you're supposed to do, but perhaps not since the function returns an address different than the address of the account singing the message. 

**🔢 Code to reproduce bug**

Client side code (Typescript):

```            
            let contract_address = await TokenHelper.deploy();
            let hm = await ethers.getContractAt("HiveMind", contract_address)
            let message : string = "check that this message was signed by account0";
            //hash the plain text message; 
            let messageHash = keccak256(utils.toUtf8Bytes(message));
            //account0 signs the message;
            let signature = await address0.signMessage(utils.toUtf8Bytes(messageHash));
            //verify the message
            let output = await hm.connect(address0.address).verifyMessage(message, signature);
            console.log(`Actual address:    ${address0.address}`)
            console.log(`Recovered address: ${output[0]} ${output[1]}`);
            console.log("");
            console.log("ethers.js version", ethers.version)      
```
Output   

TokenTest
```
Actual address:    0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
Recovered address: 0xB21D540039aB6A0F01b01c0b7bccdC887B67Bc56 false
ethers.js version ethers/5.4.7
```

Contract Code:
```
function verifyMessage(string memory message, bytes memory signature) 
        public view  returns(address, bool) {
        //hash the plain text message
        bytes32 messagehash =  keccak256(bytes(message));
        bytes memory sig = abi.encodePacked(signature);
        address signeraddress = messagehash.toEthSignedMessageHash().recover(sig);
              
        if (msg.sender==signeraddress) {
            //The message is authentic
            return (signeraddress, true);
        } else {
            //msg.sender didnt sign this message.
            return (signeraddress, false);
        }
    }
```

**Comment by Amxx** [comment]
You shouldn't need to do `bytes memory sig = abi.encodePacked(signature);`  in the verify message. (it should actually not change anything, so that is not the main issue)

Note that a 65 bytes long signature, when written in hex format, takes 132 chars (2 for the `0x` prefix, and 2 for each bytes written in hex)

I'm not seeing anything obvious right now, but what I tell you with 99.9% certainty is that this library works, and that its most likely a minor mistake in the way you generate them.

In the repo tests you can see it working with strings using web3js ... and here is an example of it working with non-string messages:
- sign: https://github.com/OpenZeppelin/workshops/blob/master/06-nft-merkle-drop/test/1-ERC721LazyMint.test.js#L31
- verify: https://github.com/OpenZeppelin/workshops/blob/master/06-nft-merkle-drop/contracts/ERC721LazyMint.sol#L21-L38

If you just replace the hash of `(uint address)` in this example, with a hash of `string` should get something that works.

**Comment by frangio** [comment]
Ok, @julianmrodri had the answer but it wasn't `solidityKeccak256`. :smile:

@grapevinegizmos The problem is that you're calling `address0.signMessage(utils.toUtf8Bytes(messageHash))`. This is signing the string corresponding to the hex encoded message hash, as opposed to the actual bytes of the message hash.

The fix is to use `arrayify`:

```
await address0.signMessage(utils.arrayify(messageHash))
```

I've confirmed that this recovers to the correct address.
