### ISSUE TITLE
dangerous use of `super`

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2936]
### Background
In Solidity, `super` does **not** always refer to the closest parent of the contract where it is defined.

When `D.foo` is called, it calls `B.foo`. That will **not** call `A.foo`, which may be surprising for developers.

```
contract Logger {
    event Log(string s);
}

contract A is Logger {
    function foo() public virtual {
        emit Log("A.foo");
    }
}

contract B is A {
    function foo() public virtual override(A) {
        emit Log("B.foo entered");
        super.foo();
        emit Log("B.foo left");
    }
}

contract C is A {
    function foo() public virtual override(A) {
        emit Log("C.foo");
    }
}

contract D is C, B {
    function foo() public override(B, C) {
        super.foo();
    }
}
```

There are many places in `@openzeppelin/contracts` where `super` is used, e.g.:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/extensions/ERC20Pausable.sol#L29

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/access/AccessControlEnumerable.sol#L61

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/governance/extensions/GovernorTimelockControl.sol#L125

### Security vulnerability
Alice is a developer that uses OpenZeppelin libraries. She uses library `B` in the above code snippet, expecting that `super.foo()` will call `A.foo`. However, it calls `C.foo`. If this is discovered during runtime this can lead to unexpected outcomes.

### Recommendation
Specify the contract instead of doing `super`. E.g. in the above code snippet, `B` would become:

```
contract B is A {
    function foo() public virtual override(A) {
        emit Log("B.foo entered");
        A.foo();
        emit Log("B.foo left");
    }
}
```

This will improve readability and ensure that Alice's code calls `A.foo`. If Alice wishes different behavior instead of `A.foo`, she can still do that by overriding `B.foo`. This approach is more explicit and less prone to errors.

**Comment by Amxx** [comment]
Hello @hacker-DOM 

Lets take the example of `_beforeTokenTransfer`

- If is defined in ERC20.sol with an empty body
- It is overridden in ERC20Pausable, ERC20Snapshot, and possibly more contracts in the future.

If the extensions, that override this "hook", we want to call super to chain the hooks, regardless of the inheritance order. Basically we want both

```
contract A is ERC20Pausable, ERC20Snapshot {}
contract B is ERC20Snapshot, ERC20Pausable {}
```

To call the hooks in both extensions.

If we did the call to `ERC20._beforeTokenTransfer`, then only we be in trouble. The users would have to explicitly call the hooks in all relevant extensions, and pray that there is nothing shared in the inheritance tree that would cause some hooks non-trivial to be called twice.

Te same approach applied to ERC165's `supportsInterface`

**Comment by frangio** [comment]
Thank you for this report @hacker-DOM.

I want to remind you first of all that if you uncover a security vulnerability in OpenZeppelin Contracts we ask you to first responsibly disclose it to us at `security@openzeppelin.com`, as documented [in our security policy](https://github.com/OpenZeppelin/openzeppelin-contracts/security/policy#reporting-a-vulnerability).

---

We disagree that `super` is dangerous. In fact, I would argue what is dangerous is exactly the opposite: not using `super`. In your particular example, the bug is in the definition of `C.foo`, which does not invoke its parent `A.foo`, and this is what causes `A.foo` to never be invoked in the chain. In some cases this might even be intentional and not a bug, after all `C` is explicitly overriding `A`'s definition and replacing it with its own.

Note that [our documentation states](https://docs.openzeppelin.com/contracts/4.x/extending-contracts#rules_of_hooks) that hooks such as `_beforeTokenTransfer` should always be overriden including the `super` call.

I believe the source of the confusion here is, in part, Solidity's syntax of `override(A)`. It hides the fact that the immediate parent is _not_ necessarily `A`.

**Comment by cameel** [comment]
@frangio 
> I believe the source of the confusion here is, in part, Solidity's syntax of `override(A)`. It hides the fact that the immediate parent is _not_ necessarily `A`.

Any suggestions on how you would change it? If `override(A)` gives a false impression that `A.foo()` would always be called you can write just `override` without naming the contract (at least as long as it inherits from only one base). The contract that will actually be called cannot be listed there because it cannot be determined based on `B`'s definition alone. It depends on what other contracts the contract that derives from `B` inherits from and can be different for different derived contracts. So it's `C.foo()` here but could also be `A.foo()` for another case, with the same exact definition of `A`.

Also, I agree that `super` is not inherently dangerous, in fact it's needed to solve some problems with multiple inheritance, but it also is confusing to users who haven't carefully thought through of the consequences of that kind of inheritance. We have an issue to improve it so feel free to post any new ideas there: https://github.com/ethereum/solidity/issues/7261. Unfortunately we haven't come up with anything clearly better so far.

**Comment by cameel** [comment]
Ah, based on https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2937#issuecomment-961484068 I see that dropping the name of the contract from `override(A)` was what you were actually suggesting.

Anyway, `super` does have its share of issues so any input in the issue I linked to is welcome.
