### ISSUE TITLE
`ERC20PresetFixedSupply` may have tokens minted

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2942]
### Description
One of the ancestors of `ERC20PresetFixedSupply` is `ERC20`, which contains:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/ERC20.sol#L243-L262

This function is also available in `ERC20PresetFixedSupply`.

### Recommendation
Rename `ERC20PresetFixedSupply` to `ERC20PresetInitialSupply`. Alternatively, consider overriding the function `_mint` and replacing 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC777/presets/ERC777PresetFixedSupply.sol#L28

with `ERC20.mint`.

**Comment by Amxx** [comment]
Hello @hacker-DOM 

Presets are contracts that are "ready to use" and that provides the expected behavior if you do not modify them. Unlike extensions, they are not designed to be inherited and expanded upon.

Preset are also being deprecated in favor of the [wizard](https://wizard.openzeppelin.com/).
