### ISSUE TITLE
Inheritance assymetry

### ISSUE THREAD

**Issue by hacker-DOM** [OpenZeppelin/openzeppelin-contracts#2943]
### Description

At most locations in the code, inheritance is done without redunancy, e.g.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC777/ERC777.sol#L29

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC777/presets/ERC777PresetFixedSupply.sol#L15

However, there are locations where there is an inheritance redunancy, e.g.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/ERC20.sol#L35

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/ee149877212acf5564921244b3cdaa7266a372fe/contracts/token/ERC20/extensions/ERC20Burnable.sol#L14

### Recommendation
We recommend not having any redunancy in inheritances. This makes the codebase easier to understand and read.

**Comment by Amxx** [comment]
Hello @hacker-DOM 

Some contract are treated in a particular way, because it could be unsafe to have them not be the first one in the inheritance tree. This is, in particular, the case of `Initializable`.

To avoid any issue, we have an unwritten rule to ALWAYS inherit Context as the first child if `_msgSender` is used in the contract, regardless of weither it is indirectly inherited or not.
