### ISSUE TITLE
unchecked - what does it do?

### ISSUE THREAD

**Issue by nbawe** [OpenZeppelin/openzeppelin-contracts#2963]
In the case of the following function what does the `unchecked` do? Isn't `require` enough? The code originates from [ERC20.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol).
```
function transferFrom(
        address sender,
        address recipient,
        uint256 amount
    ) public virtual override returns (bool) {
        _transfer(sender, recipient, amount);

        uint256 currentAllowance = _allowances[sender][_msgSender()];
        require(currentAllowance >= amount, "ERC20: transfer amount exceeds allowance");
        unchecked {
            _approve(sender, _msgSender(), currentAllowance - amount);
        }

        return true;
    }
```

**Comment by julianmrodri** [comment]
By default Solidity now includes checks for underflow/overflow on arithmetic operations. But sometimes you can avoid them to save some gas if you are really sure the operation won't cause any underflow/overflow. 

In this case because the `require` is already validating that `currentAllowance >= amount` then you don't need to check for overflow the `_approve`. 

The `unchecked` in this case is  an optimization in terms of gas, not mandatory to use but useful in cases like this.
