### ISSUE TITLE
send" and "transfer" are only available for objects of type "address payable", not "address".

### ISSUE THREAD

**Issue by robinportigliatti** [OpenZeppelin/openzeppelin-contracts#3008]
Hello,

I am working on an NFT contract and can't figure how to withdraw the ETH from the contract when all my NFT will be minted.

I used the version 4.4 of the project openzeppelin-contracts
```
pragma solidity >=0.4.22 <0.9.0;

import "/app/openzeppelin-contracts/contracts/token/ERC721/extensions/ERC721Enumerable.sol";
import "/app/openzeppelin-contracts/contracts/utils/Counters.sol";
import "/app/openzeppelin-contracts/contracts/access/Ownable.sol";
import "/app/openzeppelin-contracts/contracts/utils/math/SafeMath.sol";

contract SimpleContract is Ownable, ERC721Enumerable {

  function withdraw() public onlyOwner {
          uint balance = address(this).balance;
          msg.sender.transfer(balance);
      }
}
```

Here is the error message:
```
Error: "send" and "transfer" are only available for objects of type "address payable", not "address".
   --> <stdin>:102:9:
    |
102 |         msg.sender.transfer(balance);
    |    
```
I got the example from BAYC contract: https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#code

Do you know a way to implement this ? The only thing I see different is the code separation from `ERC721` and `ERC721Enumerable`.

Thanks,

**Comment by Amxx** [comment]
Hello @robinportigliatti 

Address payable was introduced by solidity 0.6.0, about 2 years ago. [This is documented in their changelog (which also include a section "how to update your code")](https://docs.soliditylang.org/en/v0.8.10/060-breaking-changes.html#semantic-and-syntactic-changes).

I would also point out that using `msg.sender.transfer(balance)` is also not recommended since 2019: [Check out this article to know more](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/).

I would encourage you use `Address.sendValue` instead (provided by `utils/Address.sol`)

**Comment by robinportigliatti** [comment]
Thanks for the feedback
Here is what the function looks like with your recommendations:
```
    function withdraw() public onlyOwner {
        require(!withdraw_locked, "Reentrant call detected");
        withdraw_locked = true;

        uint256 amount = address(this).balance;
        Address.sendValue(payable(msg.sender), amount);

        withdraw_locked = false;
    }
```

**Comment by robinportigliatti** [comment]
And the ethers.js v5 implementation for prosperity:
```
  const signer = provider.getSigner()
  const contractInstance = new ethers.Contract(contract_address, abi, signer)
  let nonce = await signer.getTransactionCount()
  nonce = ethers.utils.hexValue(nonce)
  let  = await provider.getNetwork()
  gasPrice = ethers.utils.hexValue(BigInt(gasPrice.toString()))
  let gas = await contractInstance.estimateGas.withdraw()
  let value = ethers.utils.hexValue(0)

  let data = await contractInstance.functions.withdraw({
    "gasPrice": gasPrice,
    "gasLimit": gas,
    "nonce": nonce
  })
```

**Comment by abu-bakarr** [comment]
Hello you can solve it by 

`  function withdraw() public onlyOwner {
          uint balance = address(this).balance;
          address payable owner = msg.sender;
         owner.transfer(balance);
         }`

**Comment by Amxx** [comment]
@abu-bakarr & Others

[Please don't use `.transfer`](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/)

OpenZeppelin Contract includes `Address.sendValue` which is way safer.

**Comment by RafaDSan** [comment]
> @abu-bakarr & Others
> 
> [Please don't use `.transfer`](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/)
> 
> OpenZeppelin Contract includes `Address.sendValue` which is way safer.

Hello, Amxx. I have checked the link you provided (https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/) and in the article is said to use "call" instead.  For example, instead of using the following line:     
msg.sender.transfer(amount);

**Comment by RafaDSan** [comment]
> @abu-bakarr & Others
> 
> [Please don't use `.transfer`](https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/)
> 
> OpenZeppelin Contract includes `Address.sendValue` which is way safer.

Hello, Amxx. I have checked the link you provided (https://consensys.net/diligence/blog/2019/09/stop-using-soliditys-transfer-now/) and in the article is said to use "call" instead. For example, instead of using the following line: `msg.sender.transfer(amount);`                                                                                                                                                                                                                                                                                                                     It's recommended to use the line with call                                                                                                                                                    `(bool success, ) = msg.sender.call.value(amount)("");`                                                                                                                 
Does it still stand true? Or is even safer to use Address.sendValue at the moment?

**Comment by Amxx** [comment]
`Address.sendValue` is a wrapper around `call` that check the success. Both are equivalent

**Comment by RafaDSan** [comment]
I understood now, thx!

Em ter., 24 de mai. de 2022 às 04:10, Hadrien Croubois <
***@***.***> escreveu:

**Comment by Keyur5123** [comment]
Hello,guys 
this is my structure and function defintion am getting same error in my machine please help me out to solve this...

  struct Image {
    uint id;
    string hash;
    string description;
    uint tipAmount;
    address payable author;
  }

images[1] = Image(imageCount, _imgHash, _description, 0, msg.sender);


am not able to use msg.sender
