### ISSUE TITLE
Simpler ERC721Enumerable and ERC721 implementations for 5x cheaper mint

### ISSUE THREAD

**Issue by syffs** [OpenZeppelin/openzeppelin-contracts#3028]
**🧐 Motivation**
Regular ERC721 minting gas cost is quite high, which leads to huge carbon footprint and high costs

**📝 Details**
I've come accross a [simplified version of OpenZeppelin ERC721Enumerable](https://etherscan.io/address/0x0f78c6eee3c89ff37fd9ef96bd685830993636f2#code#F4#L1) and [ERC721](https://etherscan.io/address/0x0f78c6eee3c89ff37fd9ef96bd685830993636f2#code#F6#L1)  which roughly divide gas by 3 to 5 or more (depending on the number of token you mint per tx).

I've performed a benchmark using the below contract:
```solidity
contract SimplerERC721Test is ERC721Enumerable, Ownable {
    address[] internal _test;
    string public baseURI = "";
    uint256 public maxTokensPerWallet = 100;

    constructor() ERC721("SimplerERC721Test", "SET") { }

    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        require(_exists(tokenId), "Token does not exist.");
        return string(abi.encodePacked(baseURI, Strings.toString(tokenId)));
    }

    function mintFree(uint256 number) public {
        uint256 supply = totalSupply();
        for( uint i; i < number; ++i ) {
            _safeMint(msg.sender, supply + i);
        }
    }

    function mintLimit(uint256 number) public {
        require(balanceOf(msg.sender) < maxTokensPerWallet, "Exceeds max per wallet");
        mintFree(number);
    }

    function mintLimit10(uint256 number) public {
        mintLimit(number);
    }

    function mintLimit20(uint256 number) public {
        mintLimit(number);
    }
}
```
and the below test in hardhat:
```ts
  it('should mint a bunch', async () => {
    const helpMintFree = async (number, account, step = 50) => {
      const iter = Math.floor(number / step);
      const rest = number % step;
      for (let i = 0; i < iter; i++) {
        await contract.connect(account).mintFree(step);
      }
      await contract.connect(account).mintFree(rest);
    };
    await helpMintFree(5, accounts[1]);
    await helpMintFree(2000, accounts[2]);
    await helpMintFree(5, accounts[1]);
    await helpMintFree(7000, accounts[2]);
    await helpMintFree(1, accounts[1]);
    const balance = await contract.connect(accounts[1]).balanceOf(accounts[1].address);
    assert(balance.eq(11));

    await contract.connect(accounts[1]).mintLimit(1);
    await contract.connect(accounts[1]).mintLimit10(10);
    await contract.connect(accounts[1]).mintLimit20(20);
  })
```

Here is the gas report with OpenZeppelin implementation:
![image](https://user-images.githubusercontent.com/4192037/146284543-6621ff10-ef73-483f-8dcd-d4ca8a5fce37.png)
and now with the simplified implementation:
![image](https://user-images.githubusercontent.com/4192037/146284883-55b3daf3-bdef-4843-ad41-71543b95f58c.png)

I only see 2 downsides:
* calling balanceOf in a tx would skyrocket the gas: this is easily fixed by adding back the _balance mapping (which I did in my test)
* tokenIds have to be generated in order from 0: which is the case 99% of the time on NFT collections

The difference is huge, so I'm wondering whether there are any security/functional blindspots or considerations that I'm missing ?

**Comment by Amxx** [comment]
Hello @syffs and thank you for raising this issue.

Gas cost of minting NFTs is indeed very important, and it's something that is certainly worth optimizing. Your number looks very promising.

We will definitely experiment to replicate your results, but I would like to point out two things:

- ERC721Enumerable is known to be very ineffective. That is because it stores a lot of data that is not essential to the life of the NFT. Since 4.0.0 it is no longer part of the core ERC721 contract, and we encourage people not to use this extension if they don't really need it!

- You say that:

> tokenIds have to be generated in order from 0: Which is the case 99% of the time on NFT collections

My experience tells me otherwise, and I'd love to see statistics about the "99%" number.

**Comment by Amxx** [comment]
Upon a further look at the codebase your linked, I am dubious this is the right approach.

While it looks like an Openzeppelin implementation, it is definitely not. If their `ERC721` implementation is much cheaper to use, its because it basically stores nothing more then the owner of the token. It doesn't keep track of the balances and it assumes that tokens are minted sequentially. This has two consequences:
- the complete loss of generality;
- the tremendous cost of querying any "enumerability" function.

As we often stated, OZ is not shooting for extreme gas optimization, but for modularity and generality. We assume any use that matches the ERC standard should be achievable using our contracts. There is room in this space for other implementations that are optimized for very specific usecases, but it's "in addition to" our generic contract, not "in place of".

I would had that I'm worried about the interoperability of this contract. Any third party that would use the return value of "balanceOf" would revert for users with too many tokens. This means that in some cases, DoS attacks would be possible by dropping tokens to the target's wallet.

**Comment by syffs** [comment]
Thanks for the quick response @Amxx !

I realized ERC721Enumerable was inefficient, but I didn't know you weren't encouraging its usage: good to know

> My experience tells me otherwise, and I'd love to see statistics about the "99%" number.

I'm clearly getting ahead of myself with the "99%" number: I'd usually point out such approximation in someone's else mouth, so I clearly wrote this too fast.. Sorry about that ! And your guess is likely to be much more educated than mine.

That said a more accurate wording would be: I feel like most of the popular and/or recent collections are either generating tokens sequentially or could achieve roughly the same result doing so.

Here are a few examples:
- [BAYC](https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#code)
- [WorldOfWomen](https://etherscan.io/address/0xe785e82358879f061bc3dcac6f0444462d4b5330#code#F1#L1)
- [Mekaverse](https://etherscan.io/address/0x9a534628b4062e123ce7ee2222ec20b86e16ca8f#code#F3#L1)
- [NuclearNerds](https://etherscan.io/address/0x0f78c6eee3c89ff37fd9ef96bd685830993636f2#code#F1#L1)

> It doesn't keep track of the balances

Indeed, I initially pointed this out, and suggested to add the _balance mapping back, which should keep us safe from the point you mentioned above ?

> it assumes that tokens are minted sequentially

The contract I listed above either use Enumerable for its `totalSupply` method or some kind of counter to keep track of ids. So I feel that if your contract is intended to do that, defining _owners as an array makes it simpler for enumerability than using the whole ERC721Enumerable. 

> As we often stated, OZ is not shooting for extreme gas optimization, but for modularity and generality. We assume any use that matches the ERC standard should be achievable using our contracts. There is room in this space for other implementations that are optimized for very specific usecases, but it's "in addition to" our generic contract, not "in place of".

Of course, I agree 100% with that, and this is why it's a feature request ! Now, for  a number of contracts generating tokenIds sequentially, wouldn't a dedicated implementation make sense ?

**Comment by syffs** [comment]
To be fair, I'm quite new to solidity and smart contract development ! I assumed that ERC721Enumerable was the way to go to keep track of your supply. Which is clearly wrong.

After testing the OZ ERC721 + Counter implementation:
![image](https://user-images.githubusercontent.com/4192037/146366460-b192304a-26d2-4ff0-8a5d-89fe08a4105f.png)
Which is fairly close to the previous results with the custom ERC721Enumerable.

My conclusion is to ban ERC721Enumerable from any future implementation.

I'll close this, but maybe it should be made more clear, that ERC721Enumerable is to be avoided ?
