### ISSUE TITLE
The ability to override ERC20Upgradeable _transfer function

### ISSUE THREAD

**Issue by iam-dev** [OpenZeppelin/openzeppelin-contracts#3093]
**🧐 Motivation**
see also: https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/issues/139
When override ERC20Upgradeable _transfer function using:
```
function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual override(ERC20Upgradeable) {}
```
 You need to add mapping(address => uint256) private _balances; on the parent contract., resulting 0 balances when transfering a token.

As for now you can't add feature like adding tax to all transfers

**📝 Details**
Add _processTransfer within ERC20Upgradeable _transfer function.

```
function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual {
        require(sender != address(0), "ERC20: transfer from the zero address");
        require(recipient != address(0), "ERC20: transfer to the zero address");

        _beforeTokenTransfer(sender, recipient, amount);

        uint256 senderBalance = _balances[sender];
        require(senderBalance >= amount, "ERC20: transfer amount exceeds balance");
        _processTransfer(sender, recipient, amount);

        emit Transfer(sender, recipient, amount);

        _afterTokenTransfer(sender, recipient, amount);
    }

function _processTransfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual {
        unchecked {
            _balances[sender] -= amount;
        }
        _balances[recipient] += amount;
    }
```

**Example implementation**
```
function _transfer(
        address sender,
        address recipient,
        uint256 amount
    ) internal virtual override(ERC20Upgradeable) {
        require(sender != address(0), "ERC20: transfer from the zero address");
        require(recipient != address(0), "ERC20: transfer to the zero address");

        _beforeTokenTransfer(sender, recipient, amount);

        uint256 senderBalance = balanceOf(sender);
        require(senderBalance >= amount, "ERC20: transfer amount exceeds balance");

        uint256 newAmount = amount;
        if (!_midSwap) {
            if (!hasRole(EXCLUDED, sender) && !hasRole(EXCLUDED, recipient)) {
                // TAX SETUP
                uint256 taxAmount = newAmount * _tax / _DIV;
                super._processTransfer(sender, _thisAddress, taxAmount);
                newAmount -= taxAmount;
                emit Transfer(sender, _thisAddress, taxAmount);
            }
        }

        super._processTransfer(sender, recipient, newAmount);
        emit Transfer(sender, recipient, newAmount);

        _afterTokenTransfer(sender, recipient, newAmount);
    }
```

**Comment by Amxx** [comment]
Hello @iam-dev 

When overriding the _transfer function, you are expected to use super calls to performs underlying transfers. This is showcased in many places in our codebase. In particular, I'm thinking of ERC20Votes.

An example that is often discussed, is adding fees to a transfer operations. This can be done easily that way:
```
function _transfer(address sender, address recipient, uint256 amount) internal virtual override {
    uint256 fee =  amount * feePercentage / 100;
    super._transfer(sender, feeRecipient, fee);
    super._transfer(sender, recipient, amount - fee);
}
``` 

The reason why balances are private is the same reason why we are not going to implement your `_processTransfer`: It would allow balances to change without a transfer event being emitted, and that would break the ERC20 compliance of the contract.

**Comment by Amxx** [comment]
Additional comments:

- You way of cutting between `_transfer` and `_processTransfer` means that `_processTransfer` is not protected.
  - it would be possible to overflow negatively, meaning that it is possible to take more token from the actual balance (unchecked would allow do that), and causing balance to jump to huge values.
  - it would allow to send from/to address(0), which is not allowed in our system.
- `_processTransfer` doesn't not emit a Trnasfer event (inconsistent with the ERC)
- `_processTransfer` doesn't not call the hooks, meaning that some token movement would be watched by other module, resulting in dangerous undefined behavior.

To ensure the security and consistency of the contracts, transfers should:
- only be allowed if "from" balance is sufficient
- only be allowed if sender and recipient are non 0 (otherwise, use mint or burn)
- emit a transfer Event
- call the corresponding hooks.

This means that IMO, ERC20._transfer is minimal, and nothing smaller (in terms of features) should be available, as calling it would break some assumptions.

We are expecting contract developers to call `_transfer` for any token transfer operation. Additional "on transfer" features can easily be added through the before and after hooks ... and more drastic operation (adding fees for example) can be done by overriding `_transfer` and using the super keyword.

IMO, what you are proposing is not necessary (I honestly don't see the usecase) and extremely dangerous (you could very easily use it to create "hidden" bugs, willingly or not).

**Comment by iam-dev** [comment]
Let's discuss.

Your propose solution does not work for me. I need to override the entire _transfer.  Override _transfer and _beforeTokenTransfer at the same time, giving weird issues like doing transfers multiple times

```
function _transfer(address sender, address recipient, uint256 amount) internal virtual override {
    if (!_midSwap && !hasRole(EXCLUDED, sender) && !hasRole(EXCLUDED, recipient)) {
        uint256 taxAmount = amount * _tax / _DIV;
        super._transfer(_thisAddress, taxAmount);
        amount -= taxAmount;
    }
    super._transfer(recipient, amount);
}
```

**Comment by rt9k35rfpk** [comment]
@Amxx what is the `_midSwap` related to? 😎

**Comment by Amxx** [comment]
I don't know, this was part of @iam-dev original post.
