### ISSUE TITLE
VestingWallet.sol unusable on a private network

### ISSUE THREAD

**Issue by soragXYZ** [OpenZeppelin/openzeppelin-contracts#3140]
Hi! 

I had a very weird behavior with this [contract](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/finance/VestingWallet.sol)
I deployed it on rinkeby and it's working like a charm as you can see [here](https://rinkeby.etherscan.io/address/0x85cfac58C8C8a35001DA8153535d1778995604D8#readContract)
I can deploy the contract, send some ERC20 tokens and then retrieve them later

The **same** contract isn't working on my private network

**💻 Environment**

Contract: VestingWallet.sol
Deployed with hardhat
Solidity version 0.8.4
Private network with gas price null deployed on Azure using this [repo](https://github.com/ConsenSys/quorum-kubernetes) with Besu
[Faulty contract](http://20.103.56.17/address/0x6E9e64d6E2E40C161EC486Ae8BCD90abddC71Acd/transactions)

**📝 Details**

I can't do anything with the contract, view functions do not return anything, and when trying to use a write function, the transaction is reverted (bad instruction). [Example here](http://20.103.56.17/tx/0xc97a6986058c0ec136fc5dd39b73f7e6c27e5d31ec5820c3edc13b8ba13e8add/internal-transactions)

I have absolutely no idea about what is going on

**Comment by Amxx** [comment]
Hello @soragXYZ 

You are getting "Error: Bad instruction". This probably comes from a difference of EVM version between your private network and the compiler settings your used. That might be because the contract does `address(this).balance`. There is now an opcode for that (since Istanbul), that used not to exist. The compiler probably uses it, and you networks doesn't support it.

Solution: 
- Set your compiler to an older version of the EVM (last before istambul was petersburg)
- Upgrade your private network to support [eip-1884](https://eips.ethereum.org/EIPS/eip-1884)

**Comment by soragXYZ** [comment]
Hello @Amxx 

Indeed, this was the issue! Thanks a lot
