### ISSUE TITLE
ERC1155Supply hook into _beforeTokenTransfer causing overflows when attempting to burn more than totalSupply

### ISSUE THREAD

**Issue by antonklyr** [OpenZeppelin/openzeppelin-contracts#3141]
Hello,

I have recently updated from 4.2 to 4.4, and noticed a change in ERC1155Supply moving supply tracking to the _beforeTokenTransfer hook, and although I enjoy not having to mention ERC1155Supply in the override chain of all the methods it used to override, that change has brought another issue:

The ERC1155Supply extension is now doing arithmetic on transferred tokens before any check on the transferred amount has been done, causing a panic code for underflowing outside an unchecked block in the case of an attempt to burn more tokens than the current total supply.

I am not sure this qualifies as a bug, as it may be an intended behavior, but since I'd selfishly like to rely on this library to revert with neat messages in such cases, I'm still reporting it!

Thank you for your time.

**💻 Environment**

OpenZeppelin 4.4, Hardhat

**Comment by Amxx** [comment]
Hello @antonklyr 

I think we both agree that the transaction should revert if the burn operation is larger than the balance of the user, or the totalSupply for this token.

I would agree that in the second case, we should probably get a proper error and not an arithmetic overflow. @frangio what is your opinion on that?

Lets discuss how we could fix that:
1. We could add a check in `_burn` on line 325 of `ERC1155.sol`. We shouldn't however remove the check on line 329 because there is always a risk of `_beforeTokenTransfer` minting, burning, or transferring assets. We would have a double check, which is not nice, in particular because it would be paid by contract that don't need it.
2. We could add a check in `ERC1155Supply.sol` between line 53 and 54.
3. We could make line 54 of `ERC1155Supply.sol` unchecked, and rely on the overflow being catched latter (if the amount overflows the totalSupply, then surely it overflows the balance).

Option 3 is the cheaper, but feels dangerous, because other overrides of "_beforeTokenTransfer" will be seeing an invalid state.

I'd personally go for option 2.
