### ISSUE TITLE
ERC1155Supply: Add totalSupply() function that returns overall supply count

### ISSUE THREAD

**Issue by philipSKYBIT** [OpenZeppelin/openzeppelin-contracts#3301]
**🧐 Motivation**
[ERC1155Supply](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.5.0/contracts/token/ERC1155/extensions/ERC1155Supply.sol) only counts by token ID. In some cases we may want a general overall count of all tokens that have been minted under the contract. e.g. etherscan and polygonscan tries to call `totalSupply()` when showing information about an NFT, and shows an error on the page if it failed.

![image](https://user-images.githubusercontent.com/70418730/160549007-4e049561-814a-4084-a9c8-fb0052bccab3.png)

**📝 Details**
Having only a count for each token ID in `ERC1155Supply` means to get an overall total count, options are:

- loop through all minted token IDs and call `totalSupply(id)`
- or not use `ERC1155Supply` and within the ERC1155 contract:
-- use [Counters](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Counters.sol). But `Counters` cannot increment by more than 1, which we'd want after a batch mint. Here is an issue about this: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/3296
-- or just use `uint256` instead of both `ERC1155Supply` and `Counters`

I still want to use `ERC1155Supply` as its purpose is supply tracking. I propose to add overloaded function `totalSupply()` that returns the overall count.

Some code that could be added are:

```uint256 private _totalSupplyAll;```

```solidity
    function totalSupply() public view virtual returns (uint256) {
        return _totalSupplyAll;
    }
```
In `_beforeTokenTransfer`:
```solidity
        if (from == address(0)) {
            for (uint256 i = 0; i < ids.length; ++i) {
                _totalSupply[ids[i]] += amounts[i];
                _totalSupplyAll += amounts[i];
            }
        }

        if (to == address(0)) {
            for (uint256 i = 0; i < ids.length; ++i) {
                _totalSupply[ids[i]] -= amounts[i];
                _totalSupplyAll -= amounts[i];
            }
        }
```

**Comment by Amxx** [comment]
Hello @philipSKYBIT 

If someone wanted to track the overall token supply, the best way would indeed be to have a `uint256 _totalSupplyAll` variable, that gets incremented in the `_beforeTokenTransfer` hook. 

The reason why we don't have it is:
- When we received a request for `totalSupply` support in ERC1155, what was requested was a totalSupply per ID
- We have not, so far, seen any usecase for a totalSupplyAll.
- *A developer can easily add that himself if he/she needs it*
- Bundling it with `ERC1155Supply` would make this module even more expensive to use. Why pay for both if you possibly only need one?

**Comment by frangio** [comment]
To be fair, this variable would only get read/written on mints and burns, so I wouldn't entirely rule out adding `totalSupply()` in `ERC1155Supply`.

Before agreeing, I would like to understand the motivation a little more. What page on Etherscan tries to access this function?

**Comment by philipSKYBIT** [comment]
> What page on Etherscan tries to access this function?
On the Etherscan token page e.g.:
https://etherscan.io/token/0xddb149ae8e6635df01a530da1e46921bd78dc385
https://etherscan.io/token/0x341a1c534248966c4b6afad165b98daed4b964ef

We want to be able to show total supply minted on a minting dapp.

**Comment by frangio** [comment]
@philipSKYBIT Can you confirm on a testnet Etherscan that if there is a `totalSupply()` method in an ERC1155 token Etherscan will show its value properly?

**Comment by apecollector** [comment]
Would really be good if this was considered, I think the current supply makes the contract seem broken or non-standard conforming when viewing on etherscan:

<img width="450" alt="Screen Shot 2022-10-03 at 10 06 42 AM" src="https://user-images.githubusercontent.com/100589991/193494687-1b1aef48-0996-4448-af16-4e26b3d7298f.png">

**Comment by frangio** [comment]
Feel free to submit a pull request with this change to ERC1155Supply.

Note that the code submitted by @philipSKYBIT above is suboptimal because the global supply is updated once for each token in the batch transfer, we should optimize this by accumulating in one variable and writing to storage just once.

**Comment by Amxx** [comment]
Yes @pcaversaccio, this is something we have identified. [See this comment on the PR](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3962#pullrequestreview-1251172008).

Do you feel like this constraint would be cause real issues, or will it remain mostly theoretical. Said differently, do you know any ERC1155 contract where the supply as large enough for this value to overflow ?

**Comment by pcaversaccio** [comment]
awesome - thx for the link. So am personally not aware of any `ERC1155` contract which would be close enough to exceed `2**256-1`. Maybe it's time to run some Dune analytics :-). What I however feel is that new contract features should be _future-proof_. Since `ERC1155` has efficient minting it could be reasonable that maybe for certain, yet unknown use cases, the threshold will be breached. Or in other words, I would consider this caveat as a rather low-risk issue in the current environment but since we live in an immutable world, decisions made now can have long-lasting impacts and we're not aware of the market dynamics in 1 month, 1 year or so on (NFTs were not even part of the Ethereum White Paper iirc).

**Comment by frangio** [comment]
In any case this will never be included by default so users can make an informed decision if they decide to use this functionality.

I had also proposed to make the total supply number saturate at the max and cause the getter to revert from then on. This would be acceptable if the function is only used off chain but can't be sure about that.

**Comment by pcaversaccio** [comment]
> so users can make an informed decision

I wish this was true - how many times will people simply go to OpenZeppelin Wizard, and enable "Supply Tracking" because they read "Keeps track of total supply of tokens." which sounds like a good feature to have and that's it...

Reverting with a nice message or custom error would be indeed informative but who knows how people will interact in the future.

**Comment by frangio** [comment]
We're with you, making a library without footguns is definitely part of our design philosophy, but at some point we need to treat users like adults too. :sweat_smile: In this particular case, the reasoning for me is that this is unlikely to be a problem. If it was likely, say it capped the supply to a low number, then I would not be okay with it.

**Comment by pcaversaccio** [comment]
> we need to treat users like adults too. 

Fair enough 😎 - but just for the sake of history, I hereby make a bet that at some time in the future there will be a case where an overflow will happen and it will pose a problem (think of `totalSupply` is used as part of a weird fee calculation somewhere :-D; they will be surprised if at some point the calculation will revert or wrap, depending on the implementation). But overall I agree with you that at some point you guys need to accept certain tradeoffs. I think actually that the most important part is already done - there is an issue documenting this behavior as well as proper documentation will explain this design pattern. I actually like that you don't want to include it in `4.9.0` since it's kind of a breaking change.

**Comment by frangio** [comment]
Fixed by https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3962 in `next-v5.0`.
