### ISSUE TITLE
Unable to initialize proxy contracts deployed by another contract

### ISSUE THREAD

**Issue by ivanzhelyazkov** [OpenZeppelin/openzeppelin-contracts#3310]
I have a contract which deploys proxies pointing to a implementation. 
The implementation contains a `initialize` function which triggers the `initializer` modifier of the `Initializable` contract. 
After the deployment, in the same contract function, I call `initialize`. 
The error I get is `reverted with reason string 'Initializable: contract is already initialized'`.
The contract hasn't been initialized beforehand and the function shouldn't revert.
**The expected behavior is for the contract to be initialized.**

**💻 Environment**

Using latest version of Hardhat (`^2.9.2`) and latest versions of Openzeppelin contracts (`^4.5.0`).

Reverting to Openzeppelin contracts `^4.4.0` solves the issue.

**Comment by Amxx** [comment]
Hello @ivanzhelyazkov 

Have you checked ou the changelog for 4.4.1 and the associated breaking changes ?

**Comment by ivanzhelyazkov** [comment]
Yes - so the breaking changes in 4.4.1 are stated as follows:
`It is no longer possible to call an initializer-protected function from within another initializer function outside the context of a constructor.`
But, the function from which I'm calling the initializer-protected function isn't an initializer function.

**Comment by Amxx** [comment]
> function from which I'm calling the initializer-protected function isn't an initializer function.

Could you please prove a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that showcases what you are trying to do and what is not working?

**Comment by ivanzhelyazkov** [comment]
> > function from which I'm calling the initializer-protected function isn't an initializer function.
> 
> Could you please prove a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that showcases what you are trying to do and what is not working?

@Amxx Uploaded a repo with the example. Let me know if you have any questions.
https://github.com/ivanzhelyazkov/openzeppelin-initialize-bug-example

**Comment by frangio** [comment]
@ivanzhelyazkov In the code that you shared I'm getting a different error: "function returned an unexpected amount of data". This is because `Core` expects `initialize` to return an address as specified in [`IDeployed`](https://github.com/ivanzhelyazkov/openzeppelin-initialize-bug-example/blob/56fbf52ce64150de3c38c7305ff11d6e9078167b/contracts/IDeployed.sol#L7), but your `Deployed` implementation doesn't return anything so decoding fails. Fixing this mismatch the initializer works fine.

Whenever you use an interface you should add the interface to the inheritance list so that the compiler can check you're implementing it correctly: `contract Deployed is IDeployed` will show the error.

**Comment by ivanzhelyazkov** [comment]
Apologies for this. Looks like the problem is deeper and will require more time to reproduce - it doesn't appear to be related to a script, but to `deployments` plugin of hardhat, when creating a fixture.
