### ISSUE TITLE
ERC2981 - Let royaltyFraction (royalty fee) accessible for each tokens

### ISSUE THREAD

**Issue by DoDzilla-ai** [OpenZeppelin/openzeppelin-contracts#3379]
**🧐 Motivation**
I want to display the royalty percentage/fee (royaltyFraction) on NFTs that are listed on my marketplace app. I want my users to be acknowledged for the price cuts. 

**📝 Details**
The royalty fraction information is already recorded in a struct for each tokens' with royalty set inside the  [ERC2981.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/common/ERC2981.sol). I want to access that information and show it on my marketplace app. Currently, I have modified the [royaltyInfo](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/token/common/ERC2981.sol#L43) function to return the `royaltyFraction` like this:

```
/**
     * @inheritdoc IERC2981
     */
    function royaltyInfo(uint256 _tokenId, uint256 _salePrice) public view virtual override returns (address, uint256, uint96) {
        RoyaltyInfo memory royalty = _tokenRoyaltyInfo[_tokenId];

        if (royalty.receiver == address(0)) {
            royalty = _defaultRoyaltyInfo;
        }

        uint256 royaltyAmount = (_salePrice * royalty.royaltyFraction) / _feeDenominator();

        return (royalty.receiver, royaltyAmount, royalty.royaltyFraction);
    }
```
I have also modified the related function inside the [IERC2981](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fcf35e5722847f5eadaaee052968a8a54d03622a/contracts/interfaces/IERC2981.sol#L16) to return the royaltyInfo as follows:

```
interface IERC2981 is IERC165 {
    /**
     * @dev Returns how much royalty is owed and to whom, based on a sale price that may be denominated in any unit of
     * exchange. The royalty amount is denominated and should be paid in that same unit of exchange.
     */
    function royaltyInfo(uint256 tokenId, uint256 salePrice)
        external
        view
        returns (address receiver, uint256 royaltyAmount, uint96 royaltyFraction);
}
```

There could be a better way to achieve this. Please let us access `royaltyFraction` so users of my marketplace can also see the royalty fee (royaltyFraction) information.

**Comment by Amxx** [comment]
Hello @DoDzilla-ai 

The `royaltyInfo()` function is defined in the [ERC2981 standard](https://eips.ethereum.org/EIPS/eip-2981). I strongly advise you do NOT change the return type, as it could possibly break things.

I'm not sure what you don't like with the current `royaltyInfo()` implementation:
- it returns the address of the fee recipient
- it returns the amount of fees for a given sale price that you can set arbitrarily.

If you know, or are ready to assume, that the fees are linear, then you can very easily ask `royaltyInfo(_tokenId, 1000000)`, and divide the resulting price by 10000 to get a fee in percetages.

**Comment by DoDzilla-ai** [comment]
Hello @Amxx 

I am aware and agree with your warning about changing the return parameters in the interface. There is nothing that I don't like about the `royaltyInfo()` function. 

As I explained, I only need the royalty fraction information (percentage) without feeding any function with a `_salePrice`. Current ERC2981.sol has this information stored in it but there is no direct way to access it. It would be inefficient for smart contracts (like mine) to recalculate information that is already stored in a different contract (ERC2981.sol). And finally, that's why I am looking for a "...   better way to achieve this. Please let us access royaltyFraction so users of my marketplace can also see the royalty fee (royaltyFraction) information."

Thank you.

**Comment by Amxx** [comment]
I might be misunderstanding your use-case. What is it that needs the fee as a percentage? The contract itself? Another contract? A frontend?

The gas cost of calling `royaltyInfo(tokenId, 10000)` and then interpreting that return value is not much higher than reading the storage directly. In both cases only 1 slot is read from storage, the additional math is <100 gas. It's free if you are doing that off-chain

On the other hand, adding a new function would increase the contract size for no reasonable reason. 

Again, you can already get all the data easily, so why add cost to all users for an accessor that is technically already here?

**Comment by DoDzilla-ai** [comment]
If you check [this NFT](https://rarible.com/token/0xd7503e03d35acac4068fc7068ab0f8db7976441f:607?tab=details) on Rarible, you would see (on the right side) the "5% royalties".  This can be either calculated as you said or it could be gotten from the ERC2981.sol, which is stored as `royaltyFraction`. I want to display this percentage by getting the `royaltyFraction` without feeding the royaltyInfo with a sale price. There is no direct way to get only the royaltyFraction in the ERC2981.sol. I believe this is a missed feature (function, a getter) in ERC2981.sol.  

PS: I know royaltyFraction is not a percentage but using `royaltyInfo` with a dummy sale price is also not a direct way.

**Comment by Amxx** [comment]
What I don't understand is why you specifically DON'T want to call `royaltyInfo` with a dummy sale price? It would work just fine, and its already available as part of ERC2981.

Asking for another function to do that means that you will only be compatible with token that have this non standard function (when you could be compatible with all ERC2981 implementing contract). Its also requesting the deployer of the contract to put more bytecode onchain (which has a cost).

ERC2981 was standardized specifically so that everyone would be interoperable. I'd love to know why you want to build non-interoprable things.

**Comment by DoDzilla-ai** [comment]
- For your first and second paragraphs: I cannot make a gas cost comparison but calling `royaltyInfo` for each NFT listed on my marketplace with a dummy sale price will also run some calculations (like royalty amount) that I don't need and thus I believe unnecessary gas consumption. This is mainly what I am trying to get away from. 
- For the 3rd paragraph: I don't understand how adding a getter would break the interoperability since any other marketplace implementing the [ERC2981](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/common/ERC2981.sol) would work just fine. Additionally, the ERC2981.sol already has functions that were not **specially** defined within the [EIP-2981](https://eips.ethereum.org/EIPS/eip-2981) and it is OK since `ERC2981.sol `follows the "The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in RFC 2119."

With the addition of a simple getter, marketplaces would be able to display the royalty percentage (for sellers and buyers) without additional gas consumption of royalty amount calculation and it would be much more clear from the perspective of developers. 

Sorry If am missing something with my logic.

**Comment by Amxx** [comment]
> * For your first and second paragraphs: I cannot make a gas cost comparison but calling `royaltyInfo` for each NFT listed on my marketplace with a dummy sale price will also run some calculations (like royalty amount) that I don't need and thus I believe this would cause unnecessary gas consumption. This is mainly what I am trying to get away from.

I am going to assume you are building a website marketplace. Something similar to OpenSea. You did not say it clearly, but I guess the most logical "marketplace" case.

Calling the royaltyInfo for each NFT might indeed be a pain, but that is the design of the ERC that each NFT can have a different fee. The good thing here is that if a backend server or a website front does this call, the call is free (as far as gas is concerned). You don't pay gas when you want to check the state of the blockchain.

Now you can use the existing `royaltyInfo()` function with a dummy price ... or you could call another non standard function ... in both cases the cost will be the same.

The difference in gas cost is for whoever is going to deploy the contract. The more features there are, the most expensive it is, so you definitely don't want to deploy features that you don't need.

>     * For the 3rd paragraph: I don't understand how adding a getter would break the interoperability since any other marketplace implementing the [ERC2981](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/common/ERC2981.sol) (or anything with EIP2981) would work just fine. Additionally, the ERC2981.sol already has functions that were not **specially** defined within the [EIP-2981](https://eips.ethereum.org/EIPS/eip-2981) and it is OK since `ERC2981.sol `follows the "The key words “MUST”, “MUST NOT”, “REQUIRED”, “SHALL”, “SHALL NOT”, “SHOULD”, “SHOULD NOT”, “RECOMMENDED”, “MAY”, and “OPTIONAL” in this document are to be interpreted as described in RFC 2119." And I  (as a junior) believe adding a getter for the percentage would break any of these.

I was probably not clear to what I'm meaning by interoperability here. Its true that adding an additional function will not remove anything from the contract. Contracts would remain ERC2981 compliant, so that is not the issue.

My concern is with your marketplace relying on a specific function being present. By doing so, you are not making your marketplace ERC2981 compliant, and you will incorrectly interact with contracts that are "only" ERC2981. IMO it would be better if your marketplace doesn't make any assumptions about the contract interface beyond what is standardized in ERCs.
