### ISSUE TITLE
Utility for creating contracts

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#3415]
This issue is there to discuss the utils proposed by @pcaversaccio in #3411

**Comment by Amxx** [comment]
We personally favor contracts written in solidity and compiled using the same compiler settings. These can easily be deployed using the native solidity features. Can you tell us more about when you'd like to deploy bytecode that is not produced by the compiler?

**Comment by pcaversaccio** [comment]
@Amxx thanks for opening this issue. The motivation behind this PR is twofold:
- Provide a helper contract in the similar way it exists for `CREATE2`.
- Provide a RLP-based `computeAddress` functionality.

So let me elaborate personally when for instance I use such a `CREATE` functionality: sometimes when attacks happen I support the projects as a white hat. One of the first things I do usually is to check whether there is a similar contract on the testnets. Since the contracts are usually unverified, I take their creation bytecode and deploy them across all the chains via a helper contract that implements `CREATE` (for sophisticated attacks this won't work but I already had cases where the exploit contract where rather simple and the attackers pre-tested the attack on Rinkeby, Goerli etc.). 

Furthermore, I've seen code out there that uses the `CREATE` opcode extensively within factory smart contracts. Eventually, I've witnessed code which is not fully correct but used in production; something like:

```solidity
pragma solidity ^0.8.0;

contract DeployBytecode {
    function deployBytecode(bytes memory bytecode) public returns (address) {
        address retval;
        assembly{
            mstore(0x0, bytecode)
            retval := create(0,0xa0, calldatasize)
        }
        return retval;
   }
}
```

The problem is here that fixing the deployment code location at `0xa0` is not always correct. Also using `calldatasize` as the deployment code length without using `calldata` is not right. The overall aim is make `CREATE` a future-proof library via OpenZeppelin.

The reasoning behind `computeAddress` is that it can be really useful to precalculate the deployment address as part of e.g. a more sophisticated factory smart contract systems where certain constructor parameters are set within the deployment itself. Of course, I'm a strong advocate of `CREATE2` as well but IMO we should leave to the developer what way they chose and make sure the library they use is safe.

**Comment by pcaversaccio** [comment]
@frangio what is your view on this?

**Comment by Amxx** [comment]
> > While I'm not sure I would ever use it myself, I do understand that the "compute address" does something that is otherwise not easy to do out of the box.
> 
> Let me explain when for instance I do this: I deployed a `CREATE2` factory contract for my [`xdeployer`](https://github.com/pcaversaccio/xdeployer) plugin on 36 EVM chains. Before I do a deployment on a new chain, I always check (as part of my deployment pipeline) first whether - given my account nonce - it will be the same address as all existing ones. If the deployment is done via a clean account this is a trivial task to do but if the nonce is `>0` on all chains you need to precheck to assure everything. In any case, the method `computeAddress` can be useful in any context where no `CREATE2` factory contract is available (nor wanted) to pre-check the deployment address.

But that is something you want to check before sending the deployment transaction ... so off-chain. I don't really bet why you need a solidity implementation here.

**Comment by Amxx** [comment]
> Another use case I just realised is that you can build a clone factory via `CREATE` (and of course `CREATE2`). Depending on your needs it can be simpler to use `CREATE` since no `salt` value is involved / needs to be managed.

We already have the `Clone` library that provides create & create2 options

**Comment by pcaversaccio** [comment]
> But that is something you want to check before sending the deployment transaction ... so off-chain. I don't really bet why you need a solidity implementation here.

Because I want to test it directly against the EVM and not the `node_modules`. Also, I've already written a deployer contract (using `CREATE`) that takes the target address I want to achieve as a function parameter and uses internally the `msg.sender` & a given nonce - also as a function argument - retrieved off-chain via the RPC method `eth_getTransactionCount` to validate the correctness (via `computeAddress` before the `CREATE` call to save gas if it's wrong and reverts). Of course, you can do the same completely off-chain but I guess I follow here my own philosophy and try as much as possible via Solidity/EVM directly.

> We already have the Clone library that provides create & create2 options

Thanks for the hint - this validates this case. 

> For your message, it seems we agree that the use case is primarily for factories that would deploy contracts with arbitrary code. I'm not sure how common it is. I would always encourage users to deploy known contracts using the "new" syntax ... but there might be cases where having access to the "create" opcode with arbitrary bytecode would be relevant.

IMO yes, but I could be completely wrong of course. It's just based on my personal experience. Can't speak for the entire community.

**Comment by frangio** [comment]
I see that there could be value for deploying bytecode directly when Solidity `new` can't be used, and I think we'd be interested in offering a library for that use case so that the programmer doesn't have to drop to assembly.

I think we can reopen https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3411, though over the next week we will be focusing on the features that are already set for the next release.

**Comment by pcaversaccio** [comment]
Awesome, if @Amxx agrees as well we can move forward once you guys have wrapped up your current week's tasks.

**Comment by pcaversaccio** [comment]
For anyone still interested, I created a dedicated repo https://github.com/pcaversaccio/create-util.
