### ISSUE TITLE
Consider removing ERC165Storage

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3641]
Does it ever make sense to use this contract over ERC165 with overrides and if statements?

The API is a little simpler because it's just a call to `_registerInterface`. The use of storage makes it more expensive to execute `supportsInterface`, and also to deploy the contract. Deployment costs are not necessarily worse though, because when storage is not used it requires more bytecode, but probably not enough to match it.

**Comment by frangio** [comment]
I'm curious how many occurences we can find of ERC165Storage in the Smart Contract Sanctuary. Should give us an idea if people are using this.

**Comment by Amxx** [comment]
Its difficult to count them, as ERC165Storage is mentionned in ERC165 ...

looking "ERC165Storage," returns a lot of result (+500)

**Comment by JulissaDantes** [comment]
Looking at the total amount of contracts using the `ERC165` contract against the amount using the `ERC165Storage` inside the sanctuary with the following search criteria and results:
| Search criteria | Contract | Results Count |
|-----------------|----------|---------------|
|`repo:tintinweb/smart-contract-sanctuary file:/mainnet/ content:"contract ERC165" count:all`| ERC165 |121.4k|
|`repo:tintinweb/smart-contract-sanctuary file:/mainnet/ content:"contract ERC165Storage" count:all`| ERC165Storage |944|

We concluded that it can be removed since only ~0.8% of contracts using `ERC165` used storage to register the interfaces.

**Comment by JulissaDantes** [comment]
Implemented by #3880 .
