### ISSUE TITLE
Ownable2Step extending Ownable while keeping the one-step transfer

### ISSUE THREAD

**Issue by Artifex1** [OpenZeppelin/openzeppelin-contracts#3759]
**🧐 Motivation**
With the current `Ownable{2Step}` contracts, users can either transfer ownership in one step or two steps. There is currently no implementation to have both options in one contract. However, this would make sense for, e.g., a contract factory setup. First, the factory deploys a contract, thereby inheriting the ownership. Second, the factory transfers the ownership to an EOA in one step. Going forward, the EOA can transfer the ownership in two steps.

**📝 Details**
Within the `Ownable2Step` contract, instead of overriding the `transferOwnership` function to be a two-step transfer, extend the `Ownable` contract with a `transferClaimableOwnership` function that enables the two-step transfer, while keeping `transferOwnership` as a one-step transfer.

**Comment by Amxx** [comment]
Hello @Artifex1 

This is something we discussed for a long time in the `Ownable2Step` issue/PR.

It was decided that in `Ownable2Step`, the `transferOwnership` should be overridden so that the default is a 2 step transfer.
There was a discussion about including, or not, the one step transfer using another function (something like `forceTransferOwnership`). This was not done because it would be opinionated from us to include it by default when anyone can enable this manually in their code.

You may want to do

```
contract MyOwnable is Ownable2Step {
    function forceTransferOwnership(address newOwner) public onlyOwner() {
        _transferOwnership(newOwner);
    }
}
```
or
```
contract MyOwnable is Ownable2Step {
    function transferOwnership(address newOwner) public override onlyOwner() {
        _transferOwnership(newOwner);
    }
    function transferClaimableOwnership(address newOwner) public onlyOwner() {
        super.transferOwnership(newOwner);
    }
}
```
