### ISSUE TITLE
Consider removing ERC20VotesComp

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3833]
We released `ERC20VotesComp` for users who needed compatibility with an existing `GovernorAlpha/Bravo` instance. For 5.0, I think we can remove this contract. Anyone who still needs this compatibility can remain on 4.x, but this seems in fact very rare: I can find [1.6k deployments of `ERC20Votes`](https://sourcegraph.com/search?q=context:global+repo:tintinweb/smart-contract-sanctuary+file:/mainnet/+count:10000+contract+ERC20Votes&patternType=standard&sm=0) but only [80 deployments of `ERC20VotesComp`](https://sourcegraph.com/search?q=context:global+repo:tintinweb/smart-contract-sanctuary+file:/mainnet/+count:10000+contract+ERC20VotesComp&patternType=standard&sm=0). We should remove it from the "Compatibility" section in the Governance guide.

**Comment by frangio** [comment]
We should consider removing `GovernorCompatibilityBravo` and `GovernorTimelockCompound` as well.

**Comment by FriskyHamTitz** [comment]
Im using bravo compatibility but only that.

Instead of removing it maybe just move it to a folder called deprecated. It would be frustrating to have to be tied to separate versions of the packages just to implement contracts.

The existing contract is missing a few things which is maybe why it's use is limited because its not fully compatible with bravo. It maybe a good idea to have a fully compatible version, but if you don't feel like supporting maybe just put it in the deprecated folder like above

Things I noticed that were missing:

1.  It's missing a few properties. Proposal count, a few others
2.  There's no way to enumerate the hashes

Regardless it would be nice if all oz governance  supported a way to obtain previous proposal without using the graph or enumerating blocks on the rpc.

**Comment by Amxx** [comment]
Done in #4276

**Comment by frangio** [comment]
@FriskyHamTitz Can you please elaborate a bit more on your use case. Are you interested in the actual Bravo compatibility or are you only interested in how it stores the proposal details in storage?

**Comment by FriskyHamTitz** [comment]
I was mostly interested in bravo comparability to reduce the time it takes
to integrate into existing frontends like uniswap.

Current integrations followed what I outlined, I had to write a module to
convert the proposal count to it's original has etc and that helped speed
up integration time.
.
