### ISSUE TITLE
Redundant storeProposal in GovernorCompatibilityBravo

### ISSUE THREAD

**Issue by RitzyDevBox** [OpenZeppelin/openzeppelin-contracts#3881]
In the Bravo Compatibility Contract the proposal data is duplicated with different proposalIds
The initial Bravo Contract does not have a proposal method which takes 4 parameters,  why do we require storage for that proposalHash?

`    // ============================================== Proposal lifecycle ==============================================
    /**
     * @dev See {IGovernor-propose}.
     */
    function propose(
        address[] memory targets,
        uint256[] memory values,
        bytes[] memory calldatas,
        string memory description
    ) public virtual override(IGovernor, Governor) returns (uint256) {
        _storeProposal(_msgSender(), targets, values, new string[](calldatas.length), calldatas, description);
        return super.propose(targets, values, calldatas, description);
    }

    /**
     * @dev See {IGovernorCompatibilityBravo-propose}.
     */
    function propose(
        address[] memory targets,
        uint256[] memory values,
        string[] memory signatures,
        bytes[] memory calldatas,
        string memory description
    ) public virtual override returns (uint256) {
        _storeProposal(_msgSender(), targets, values, signatures, calldatas, description);
        return propose(targets, values, _encodeCalldata(signatures, calldatas), description);
    }
`

**Comment by frangio** [comment]
I do not understand the issue, can you please elaborate?

**Comment by FriskyHamTitz** [comment]
Why are you storing the proposal data for the 4 parameter propose?

Queue and execute, only work with proposalIds that come from the 5 parameter method

**Comment by frangio** [comment]
Right. There does seem to be a redundancy. The hashes will not be different, though. The two calls that are being done are:

```solidity
_storeProposal(_msgSender(), targets, values, signatures, calldatas, description); // (1)
_storeProposal(_msgSender(), targets, values, new string[](calldatas.length), _encodeCalldata(signatures, calldatas), description); // (2)
```

`_storeProposal` generates the hash by:

```solidity
hashProposal(targets, values, _encodeCalldata(signatures, calldatas), descriptionHash);
```

`_encodeCalldata` has the property that if `signatures[i]` is the empty string, `calldatas[i]` is passed through as is in the return value.

Note that the second call to `_storeProposal` uses `new string[](calldatas.length)`, an array of empty strings. As a result, in both cases `hashProposal` is called with the same arguments.

---

It is still an inefficiency that we should remove. I'm wondering if it has any weird interactions with inheritance that we might have to consider.

**Comment by Amxx** [comment]
I believed we did miss `super.` in the compatibility version of `propose`

Its important to notice that `_storeProposal` checks that the data is not written yet before doing the write, so we were not storing twice, and only the first store was recorded (that is the one with the signatures). Still, missing `super.` causes some unecessary operation (mostly one big hash and one sload) that we can easily avoid.

**Comment by Amxx** [comment]
> It is still an inefficiency that we should remove. I'm wondering if it has any weird interactions with inheritance that we might have to consider.

I think this is why we have this "inefficiency"!

We want modules that override the core `propose` to have the override triggered by both version of the function. This means we need the "compatibility" version to hook into the "core" version. If we simplify this workflow (as proposed in #3989) we would possibly have an external propose method that bypasses some overrides.

**Comment by frangio** [comment]
After further discussion in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3989#pullrequestreview-1270311079, we're giving this less priority because it only results in a 1% gas optimization, but are still considering options to make this better.

The reason there are two calls to `storeProposal` in the Bravo module is that the first one takes care of storing the `signatures` string and the second one doesn't know about the signatures (they are converted to function selectors by then). We need both because both functions can be used as entry points, and we need the redundancy to avoid other issues with inheritance.

One way I proposed to improve this is to keep `storeProposal` only in propose without signatures, and separately store the signatures in propose with signatures as in:

```solidity
        uint256 proposalId = propose(targets, values, _encodeCalldata(signatures, calldatas), description);
        _proposalSignatures[proposalId] = signatures;
```

If we do this, in `getActions` we need to trim off the function selectors from calldatas where signatures are available.

**Comment by frangio** [comment]
@RitzyDevBox That's what #3989 proposed. It fixes it at the cost of ignoring "downstream" overrides of `propose`. There may be important logic there that will not execute.

**Comment by frangio** [comment]
> Won't this respect downstream overrides?
> its more of the upstream ones that are the problem?

I think I meant the same as what you're saying, but upstream is a better word. "Downstream" should be defined as the direction of `super`.

> any situation where the caller does this: [...] should be okay

No, it's more complicated. It depends on the order of inheritance, and in a potentially unintuitive way due to the linearization algorithm. We need to avoid designs that change semantics depending on order of inheritance because they are very subtle and easy to miss errors.

What I mean is that if an extension is defined as `GovernorExt is Governor` and it overrides `propose`, then behavior might change for the end user depending on if they write `MyGovernor is GovernorExt, GovernorCompatibilityBravo` or `MyGovernor is GovernorCompatibilityBravo, GovernorExt`.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4073.
