### ISSUE TITLE
upgradeable proxy add version control

### ISSUE THREAD

**Issue by lxhyl** [OpenZeppelin/openzeppelin-contracts#3910]
**🧐 Motivation**

upgradeable contract is great.But maybe confusion when upgrade many times. So we can add implemenation version to better control contract.

**📝 Details**

## storage
- add `version` variable define current implemenation version. This can only increase. `version++` when admin call upgrade. 
- add `mapping(version => implemenationAddress) historyImplemenation` record hisory implemenation contract.

## method
- `backToVersion(version)` can rollback to some implemenation contract.

**Comment by Amxx** [comment]
Hello @lxhyl 

Having both a version and a mapping would make all calls to the proxy significantly more expensive. Instead of reading the implementation address (1 sload), you would have to:
- read the version (1 sload)
- hash it to get the mapping slot
- read the implementation (1 sload)

Considering this would have to be executed for every calls to the contract, it will add up to serious gas fees.


I would also argue that, beside the cost, this is not necessary at all. 

The `backToVersion` function would have to be protected. Imagine an upgrade fixes a bug, you would not want anyone to revert to a previous version that can be exploited. IMO, the `backToVersion` is already possible by using the "normal" upgrade process to use an old version. 

And you don't really need to store the history of implementations onchain. Ann upgrades should trigger an event, that can be observed off-chain.

As an exemple, you can use [this subgraph](https://thegraph.com/hosted-service/subgraph/amxx/access-control) with the following query
```
{
  accounts(where: { erc1967Implementation_not: null}) {
    id
    ERC1967ImplementationUpgraded(orderBy: timestamp) {
      transaction { blockNumber timestamp }
      implementation {
        id
      }
    }
  }
}
```
to get a history of all previous versions

**Comment by Amxx** [comment]
If you really want to have a proxy with an onchain history of versions, it should be easy to expand `contracts/proxy/Proxy.sol` and implement `_implementation()` using the mapping that you have in mind. I'm not sure this is something we want to encourage and provide to our users though.

**Comment by lxhyl** [comment]
Thank your reply,  I did not think it through.
