### ISSUE TITLE
Consider removing Context

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#3929]
`Context` provides `_msgSender()` and the reason it exists and is used across the codebase is so that the logic for getting the function caller can be replaced via inheritance, for example using `ERC2771Context`. It is necessary if we want to support overriding that logic for any piece of code in the library. While `Context` is fairly simple, it is pervasive and the vast majority of use cases do not need the functionality at all, so it's a great candidate for removal to simplify the code.

We would like to understand first if Context alternatives such as `ERC2771Context` are actively used, as well as what are the alternative recommendations we can make for those use cases.

**Comment by TrejGun** [comment]
Please correct me if I'm wrong

Context is used for transactions signed by one wallet (private key) and executed on behalf of another wallet. The most common thing I can refer to is OpenSea which makes user sign ERC20 transfer and ERC721 transfer and then both transactions are executed by the server. This is where ERC2771Context can help

But basically, any transaction can be executed by 3rd party. It is mostly a problem of security to validate transaction content. For example, https://opengsn.org/ pays gas instead of the end user. So it should be a good practice to always use Context

**Comment by frangio** [comment]
> OpenSea which makes user sign ERC20 transfer and ERC721 transfer and then both transactions are executed by the server

Can you share a reference to documentation or where we can see this being used?

**Comment by TrejGun** [comment]
I can't point to documentation because it does not exist, unfortunately( but can point to tests

wyvern protocol
https://github.com/wyvernprotocol/wyvern-v3/blob/master/test/5-wyvern-exchange-matching.js#L197

\eaport protocol
https://github.com/ProjectOpenSea/seaport/blob/main/test/basic.spec.ts#L1308

**Comment by Amxx** [comment]
Neither the [WyvernExchangeWithBulkCancellations](https://etherscan.io/address/0x7f268357a8c2552623316e2562d90e642bb538e5#code) nor [Seaport](https://etherscan.io/address/0x00000000006c3852cbef3e08e8df289169ede581#code) use Context. They both rely on msg.sender to get the caller.

In both cases they use signed messages, either using EIP-191 or EIP-712, which are independent of `Context`.

**Comment by TrejGun** [comment]
@Amxx right and your implementation of ERC721 does

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L168

so safeTransferFrom invoked by Seaport Zone will resolve _msgSender to the signer and not to Zone. 
the same will work if I call _msgSender in onERC721Received

it means I always want to use it

**Comment by Amxx** [comment]
(Almost) all our contracts use Context. We do that so that devs have the ability to override the `_msgSender` (and `_msgData`) function. Devs may for example want to override that in order to support ERC-2771 powered meta-transactions.

What we are looking for are contracts, with a pretty significant usage, that do override the Context functions.

**Comment by Amxx** [comment]
> so safeTransferFrom invoked by Seaport Zone will resolve _msgSender to the signer and not to Zone.
> the same will work if I call _msgSender in onERC721Received

When seaport calls `safeTransferFrom`, it does not pack a sender address using EIP-2771. Does it?
AFAIK, seaport works with any ERC721, and will not expect the token contract to support EIP-2771 message comming from seaport. 

Said otherwise, seaport is not an EIP-2771 relay.

We are not planning to stop using msg.sender in our contract, that would be foolish. We plan on using `msg.sender` without using `Context._msgSender()` as an alias. I don't see how this would affect seaport. The only apps that it would affect are the one that override `_msgSender()` in order to add support for some relaying mechanism.

**Comment by TrejGun** [comment]
Thanks, I see my mistake. I thought it will work for any signed transaction executed by someone else

**Comment by frangio** [comment]
Yeah, it's important to point out that the removal of Context doesn't imply that "meta transactions" of all kinds are no longer supported. What wouldn't be supported is using meta transactions to "override" the msg.sender of any piece of code in the library. But meta transaction patterns can still be implemented via signatures.

**Comment by frangio** [comment]
We have decided to keep `Context` for v5.0 based on the following:

- We've found that `ERC2771Context` has a reasonable amount of usage (see image below). This requires the use of `Context` throughout the library.
- We've confirmed that the use of `Context` and `_msgSender()` instead of `msg.sender` do not cause additional gas usage.
- The same pattern is used by [ERC721A](https://github.com/chiru-labs/ERC721A/blob/v4.2.3/contracts/ERC721A.sol#L1046), a gas-focused implementation.

We will reconsider this for v6.0. The growth of ERC-4337 infrastructure and adoption would be a contributing factor towards removal, as it can be an alternative to ERC-2771 meta-transactions.

---

Looking at Ethereum and Polygon networks:

![](https://github.com/OpenZeppelin/openzeppelin-contracts/assets/481465/9370ce37-0a1e-4838-af0d-4c5fa72d4e0d)
