### ISSUE TITLE
Improvment Bugish Behavior to ERC-721 Token Counters 

### ISSUE THREAD

**Issue by RitzyDevBox** [OpenZeppelin/openzeppelin-contracts#3991]
I'm not sure if this is the right place to report an improvement to the Contract wizard.  I generated an ERC-721 and this is the `safeMint` function that gets generated.
  
function safeMint(address to) public onlyRole(MINTER_ROLE) {
        uint256 tokenId = _tokenIdCounter.current();
        _tokenIdCounter.increment();
        _safeMint(to, tokenId);
 }

This seems like a bug to me but, its a matter of opinion.    The first Token Generated is going to be TokenId 0.

Generally Id start at 1, normally that wouldn't matter but it kinda does in solidity.  Imagine I want to keep a mapping of the token owners to the tokenId so I have a 

      `mapping(address => uint256) ownerToTokenIdMap`

Now if I were to query a nonexistant address I would get 0.  This would create ambiguity between token 0 and default behavior.  Ideally the counter should start from 1,

**Comment by Amxx** [comment]
Hello @RitzyDevBox 

The wizard provides simple example of how our contract can be used/assemble. The goal is not to provide contract that are ready to use, but rather to produce boilerplates that you will possibly modify (and audit!) before you go to production.

If you want your tokens to start at 1 instead of 0 (which is a personal choice), then you can easily do it, either by replacing 

```diff
-uint256 tokenId = _tokenIdCounter.current();
+uint256 tokenId = _tokenIdCounter.current() + 1;
```

or by adding ` _tokenIdCounter.increment();` to the constructor.

---

> Imagine I want to keep a mapping of the token owners to the tokenId so I have a

If that is your goal, you should use the ERC721Enumerable extension (that can be enabled in the wizard). Note that adding this feature signigicantly increasses the gas cost of minting/transfering tokens.
