### ISSUE TITLE
custom error instead of require statement

### ISSUE THREAD

**Issue by Sol-Devloper** [OpenZeppelin/openzeppelin-contracts#4111]
To make ERC20 gas efficient!!

Hi All,

I have been working with required statements and custom errors. Since we know "require" statements take more gas because it returns a string.

Why does openZeppline not change a "require" statement to custom errors "if" statement?

is there any particular reason "require" statements are still in the saferERC20 contract?

Thanks

**Comment by sunilsimar** [comment]
openZeppline use "require" instead of custom errors "if" , and its not changing because of certain reasons as you said its take more gas but when a require statement fails, all changes to the state of the blockchain are rolled back. This can save gas (transaction fees) in the long run, as the rest of the code doesn't need to execute if the require statement fails.
- The "require" statement makes it clear that a certain condition must be met for the code to execute. Using an "if" statement could be less clear and make the code harder to read.
- Using require statements is a widely recognized and recommended practice for creating secure smart contracts. Replacing require statements with custom error messages in an if statement could potentially introduce new security vulnerabilities if the error messages are not crafted carefully, or if the implementation of the if statement is incorrect.

Now answer to the particular reason-
"require"statements are a well-established best practice for writing secure smart contracts.if the condition not met the transaction will revert and any state changes will be undone. This can help prevent unintended behavior and protect against attacks such as reentrancy and overflows.
 you can use a "require" statement to ensure that a user has enough funds before executing a transaction, or that a certain condition is met before allowing a function to proceed.
Removing these statements would decrease the security of the contract, potentially leading to unexpected behavior and vulnerabilities.

**Comment by Amxx** [comment]
This is a duplicate of
#2839
#3614
