### ISSUE TITLE
Resolve discussion about the overflow in ERC1155Supply.

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-contracts#4344]
See https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4261/files#r1224323887

**Comment by frangio** [comment]
What we need to do is change the `_update` override in ERC1155Supply so that the supply update is done after `super._update`.

However, this introduces a reentrancy issue, so at the same time we have to refactor `ERC1155._update` so that it does not do the acceptance check at the end.

I would propose to have two functions: `_update` and `_updateChecked` where the second one calls `_update` and the transfer acceptance check. All of the token functionality would be impemented in terms of `_updateChecked`, but the override have to be done on `_update`.
