### ISSUE TITLE
AccessControlDefaultAdminRules implements IERC5313 but does not handle it in supportsInterface()

### ISSUE THREAD

**Issue by RobertOttBS** [OpenZeppelin/openzeppelin-contracts#4464]
The contract AccessControlDefaultAdminRules implements the interface IERC5313. One would expect that if we call supportsInterface() it would signal true with the interfaceId of IERC5313. However, it currently returns false.

**💻 Environment**

Used with hardhat and OpenZeppelin Version 4.9

**📝 Details**

The current implementation of supportsInterface only handles IAccessControlDefaultAdminRules and IAccessControl but does not handle IERC5313 (even though it implements the interface).

```
    function supportsInterface(bytes4 interfaceId) public view virtual override returns (bool) {
        return interfaceId == type(IAccessControlDefaultAdminRules).interfaceId || interfaceId == type(IERC5313).interfaceId || super.supportsInterface(interfaceId);
    }
```

**🔢 Code to reproduce bug**

Call of supportsInterface('0x8da5cb5b') returns false (0x8da5cb5b is the interfaceId of IERC5313)

**Comment by ernestognw** [comment]
We've previously discussed how much ERC165 support we would like to guarantee for the users, especially because we have some interfaces (eg. Governor) whose interface id changes quite often, and it's becoming difficult to keep backward compatibility.

In any case, I think this is a valid issue and we should report the IERC5313 interface in the contract because DefaultAdminRules doesn't change as often as governor does.

I'll open a PR for this but some folks are in Paris right now, perhaps we'd need to wait for approval. Thanks!

**Comment by RobertOttBS** [comment]
@ernestognw thanks a lot. I agree, the Interface IERC5313 only defines one method called 'owner()' and I don't think there is a reason to change future implementations of IERC5313 (in comparison to other, more complex interfaces like that you mentioned). I am looking forward for the PR to be processed as supporting it would be the straight forward consequence to implement the ERC5313 interface in the first place. Thanks a lot!

**Comment by ernestognw** [comment]
Hey @RobertOttBS, we decided not to support this, you can find the rationale in [this comment.](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4469#issuecomment-1654937404)

The TLDR is that ERC5313 doesn't require EIP165 and we generally think there's no reason for using it if it's specified to not rely on it.

Closing because we're strong on this opinion, but feel free to continue the conversation if there's something we're missing.

**Comment by ernestognw** [comment]
Hey @RobertOttBS, we decided not to support this, you can find the rationale in [this comment.](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4469#issuecomment-1654937404)

The TLDR is that ERC5313 doesn't require EIP165 and we generally think there's no reason for using it if it's specified to not rely on it.

Closing because we're strong on this opinion, but feel free to continue the conversation if there's something we're missing.
