### ISSUE TITLE
Coding-simplification for functions `toString` and `toHexString`

### ISSUE THREAD

**Issue by barakman** [OpenZeppelin/openzeppelin-contracts#4467]
**🧐 Motivation**
Coding simplification

**📝 Details**
Proposing a possible coding-simplification of [function toString](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L21-L44) and [function toHexString](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol#L53-L60):
```
function toString(uint256 x) internal pure returns (string memory) {
    if (x > 0) {
        string memory str;
        while (x > 0) {
            str = string(abi.encodePacked(uint8(x % 10 + 48), str));
            x /= 10;
        }
        return str;
    }
    return "0";
}

function toHexString(uint256 x) internal pure returns (string memory) {
    if (x > 0) {
        string memory str;
        while (x > 0) {
            str = string(abi.encodePacked(uint8(x % 16 + (x % 16 < 10 ? 48 : 87)), str));
            x /= 16;
        }
        return str;
    }
    return "0";
}
```
It might or might not be more gas-intense than the current implementation, but since these functions are designated primarily for testing and debugging rather than for actual deployment, I believe that the gas aspect is of low significance.

**Comment by Amxx** [comment]
> It might or might not be more gas-intense than the current implementation, but since these functions are designated primarily for testing and debugging rather than for actual deployment, I believe that the gas aspect is of low significance.

You approach is significantly more gas-intensive. I ran a simple benchmark with `1247219572055125` as an integer, and your version was 4.5 times more expensive. That is an additional 350% ... and I believe this will only get worse with longer integers or a bigger memory offset.
This is because `str = abi.encodePacked(..., str)` copies everything and expand the memory for that.

Also, this function is used in actual deployments, see `ERC721.tokenURI`
