### ISSUE TITLE
add unchecked block to save gas

### ISSUE THREAD

**Issue by carter-ya** [OpenZeppelin/openzeppelin-contracts#4548]
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/a5ed318634016a25be4000ee07044a31f363e60c/contracts/utils/math/Math.sol#L107

This method will never overflow under any circumstances. Can "unchecked" be added.

**Comment by frangio** [comment]
Yes I believe this is true because:
1. `a - 1` will not overflow because we know `a != 0`.
2. `(a - 1) / b + 1` could overflow if `(a - 1) / b` was `type(uint256).max`, but the largest number we can get is `type(uint256).max - 1` with `a = type(uint256).max, b = 1`.

Feel free to submit a PR, though it will be on hold until we start merging things for 5.1 a month from now. There needs to be a comment explaining why overflow is not possible, and there should be fuzzing.
