### ISSUE TITLE
_update(...) function might lead to poorly optimized code

### ISSUE THREAD

**Issue by liarco** [OpenZeppelin/openzeppelin-contracts#4705]
Reference: @Amxx in https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4328#issuecomment-1582098926

The proposed solution works fine whenever you want to perform an action **before** or **after** the loop, but what if you need to do something based on the value of each subtransfer? Your only option here is to run another for loop before/after the `super._update(...)` call, but then you are wasting a lot of gas by cycling twice.

I thought I could avoid this by copying the whole function body into my own contract and updating it (definitely not a clean solution, kinda hacky and risky), but turns out you can't do that because `_balances` is private, so you can't update that from a child contract.

At the moment I guess my only option is to copy the entire contract and tune it to my needs, but I think there should be a better way to achieve such a common goal.

Am I missing anything here?

Thank you for your time.

**Comment by ernestognw** [comment]
Hey @liarco, I see it could be an issue if somebody needs to perform updates based on the subtransfers, but that was also not possible in 4.x, both the before and after hooks are before and [after the whole transfer loop](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.9.3/contracts/token/ERC1155/ERC1155.sol#L224).

> but then you are wasting a lot of gas by cycling twice.

I estimate adding an operation inside the cycle or outside in another cycle wouldn't have a significant overhead aside from the extra loop counter increment, a `JUMPI` back to the start of the loop in each iteration, and `ids`/`values` accesses via `MLOAD`.

I'd expect the majority of 1155 transfers to be single asset transfers or batches with less than 5. Considering `JUMPI` gas cost is 10 and `MLOAD` will cost 3 because the memory is already expanded (no memory expansion cost), thus, I calculate the overhead of around 20-30 units per subtransfer (~100-150 units).

A PoC demonstrating a significant gas reduction would give us more hint here. If the reduction is in the order of 100-150, I wouldn't worry too much of adding a loop before/after the `_update` function.

**Comment by liarco** [comment]
Hi @ernestognw,
I can't thank you enough for the detailed response and for taking the time to provide data and examples to help me better understand your point. I totally agree, and now I see that I may have overestimated the impact of those extra for loops.

I don't have any real-world cases to present here as an example, since the one I'm working on ATM seems to be already covered by your numbers.

I'm gonna close this, thanks for your time!
