### ISSUE TITLE
Repository with new OZ version updates but with solc version 0.8.19 for projects launching on PUSH0 incompatible chains

### ISSUE THREAD

**Issue by mcgrathcoutinho** [OpenZeppelin/openzeppelin-contracts#4711]
**🧐 Motivation**
OZ's latest version contracts use v0.8.20 which require projects launching on chains like Polygon, Arbitrum to consider using older OZ versions since these EVM chains (L2s) do not support the PUSH0 opcode. I was wondering whether OZ has ever considered launching a separate repo for such chains, which includes the new version updates but with solc version 0.8.19. 

**📝 Details**

Why I think it would be good idea to launch such a repository:
1. Allowing projects launching on L2s to use the latest version updates of OZ contracts. This would make the general usage of OZ contracts more standardized in the space as well since both L1 and L2 projects would use them (just with a differentiating solc version).
2. Reduction in deployment issues faced when teams install OZ contracts ([since command provided on website installs latest version using solc v0.8.20](https://docs.openzeppelin.com/contracts/5.x/#hardhat_truffle_npm)).
3. Some devs might not be aware of the PUSH0 opcode issue that arises when using newer OZ versions.
4. In case this issue is disregarded, I would atleast recommend the team to add a note on the docs website so that deployment issues could be solved much faster.

**Comment by ernestognw** [comment]
Hey @mcgrathcoutinho, thanks for reporting.

Have you tried compiling 5.0 contracts using `paris` as the EVM version? It will produce bytecode that doesn't include `PUSH0`.

Generally, we're opposed to having variants of this repository because it increases the maintenance surface. Although I agree users can inadvertently install Contracts 5.0 and compile for `shanghai` EVM bytecode, I'd say users should look for a note regarding version compatibility in their development environments. For example, Hardhat includes [some EVM version notes in their docs](https://hardhat.org/hardhat-runner/docs/config#default-evm-version)

**Comment by mcgrathcoutinho** [comment]
Hey @ernestognw, thanks for responding.

I was probably tending towards the Shanghai version but considering the maintenance required, I think what you said makes sense. Nevertheless, I believe [this note in hardhat](https://hardhat.org/hardhat-runner/docs/config#default-evm-version) and [this one in foundry](https://book.getfoundry.sh/reference/config/solidity-compiler?highlight=evm%20version#evm_version) (although not that specific in foundry), should be referenced as a note on the OZ docs site since more people are tending towards foundry and might come across this PUSH0 error which is not explicitly mentioned in the foundry docs linked before.

**Comment by ernestognw** [comment]
An EVM version configuration will have the same issue in any other library and is not specific to OpenZeppelin Contracts. Also, ideally, this won't be an issue after the main L2s upgrade with `PUSH0` support.

I'd rather not add a note because EVM-specific configurations may be different depending on the chain and usually these specifics change relatively fast. Maintaining these compatibility-specifics was [mentioned in our previous audit (R-05)](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/audits/2023-10-v5.0.pdf) and I think we may want to work on that more generally and not just with small notes.

I'm closing because the issue was solved but not discarding any other suggestion for more general EVM compatibility.
