### ISSUE TITLE
More map types in EnumerableMap

### ISSUE THREAD

**Issue by RyanRHall** [OpenZeppelin/openzeppelin-contracts#4713]
**🧐 Motivation**
Small feature request, but I would love if EnumerableMap would support an `address => bytes32` and a `uint256 => bytes32` mapping. I have several cases where this has been useful and I end up using a `Bytes32ToBytes32Map` and then casting the key to the type I want. It works fine, but it would be cleaner if we supported the more specific types :). Happy to help contribute the changes!

**📝 Details**
Hopefully the motivation section is sufficiently clear :)

**Comment by ernestognw** [comment]
Hey @RyanRHall , I've seen a few Code4rena projects in the past using variations of EnumerableMap. This is relatively easy to implement since all variants come from a [single template](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/f7db0bea313f8b7fec0b88102acf74459f5742e9/scripts/generate/templates/EnumerableMap.js) and perhaps there's demand.

I'm adding a 5.x tag to consider this for future releases if a good discussion comes up from here.

Note that any modification shouldn't be considered audited of other variants already are.
