### ISSUE TITLE
 TypeError: No arguments passed to the base constructor. @openzeppelin/contracts": "^5.0.0"

### ISSUE THREAD

**Issue by nikitamarcius** [OpenZeppelin/openzeppelin-contracts#4717]
Issue with "@openzeppelin/contracts": "^5.0.0", when i run "npx hardhat compile", i can not compile, why i have to skip the ability to pass custom values  to constructor when deploying a contract ?

TypeError: No arguments passed to the base constructor. Specify the arguments or mark "ERC20" as abstract.
  --> contracts/ERC20.sol:10:1:
  
  Works perfect with  "@openzeppelin/contracts": "^4.9.3",

**Comment by ernestognw** [comment]
Hey, looks like you're trying to compile an ERC20 directly. In 5.0 it was changed to be an abstract contract, you just need to instantiate it:

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "[@openzeppelin/contracts/token/ERC20/ERC20.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.0/contracts/token/ERC20/ERC20.sol)";

contract MyToken is ERC20 {
    constructor() ERC20("MyToken", "MTK") {}
}
```

Now deploy `MyToken` instead of `ERC20` directly.
Closing since it's not an issue. Feel free to submit support questions in our [community forum](https://forum.openzeppelin.com/)
