### ISSUE TITLE
Use EIP-1967 for Ownable storage

### ISSUE THREAD

**Issue by pegahcarter** [OpenZeppelin/openzeppelin-contracts#4917]
**🧐 Motivation**
Access control is arguably one of the most important pieces in smart contract design.  As we move towards a future where upgradeable contracts are now the norm, access control is still as relevant, but so are storage slots.  And, as we know, storage on upgradeable contracts can be tricky.

**📝 Details**
`Ownable.sol` uses the first storage slot to store the private `_owner` address.  I propose we store the owner address similar to what is proposed in the EIP:
```
    /**
     * @dev Storage slot with the admin of the contract.
     * This is the keccak-256 hash of "eip1967.proxy.admin" subtracted by 1, and is
     * validated in the constructor.
     */
    bytes32 internal constant _ADMIN_SLOT = 0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103;
```
Currently, if implementation `A` inherits `Ownable` and implementation `B` does not, when upgrading to `B` we would have a conflict in storage space.  If we move the `_owner` to its' own storage slot (which I believe it should be anyway since it's not accessible directly by inheriting contracts), this conflict would be resolved.

**Comment by pegahcarter** [comment]
Hey @Amxx thank you.  Is there a reason why the upgradeable version isn't the de-facto?

**Comment by ernestognw** [comment]
Smart Contracts are de-facto non-upgradeable, upgradeability is a set of quirks we make to simulate upgradeability, but it comes with a bunch of constraints and considerations.

Most projects are better off writing non-upgradeable code, and in our opinion they should consciously go for upgradeability and not deal with their complexities by default.

**Comment by pegahcarter** [comment]
Are there additional costs to using the upgradeable `Ownable` that makes it more beneficial to use the non-upgradeable version?  It appears that all of the storage is private in both cases with internal/external methods to access, so the only difference should be gas.

**Comment by ernestognw** [comment]
> It appears that all of the storage is private in both cases with internal/external methods to access, so the only difference should be gas.

The main difference is that upgradeable contracts are upgradeable, just that. Of course, upgradeability comes with extra gas costs because they are exposed behind a proxy and can't take advantage of immutable variables, among other considerations.

Please refer to our [Upgradeability docs](https://docs.openzeppelin.com/contracts/5.x/upgradeable) so you can get more information. 

Personally, I think the bottom line is that if you need an upgradeable contract, you'll have to inevitably deal with the extra costs, not even optimizing would help much and may be dangerous.
