### ISSUE TITLE
Add Flexible Voting to Governor

### ISSUE THREAD

**Issue by rsolari** [OpenZeppelin/openzeppelin-contracts#4958]
**🧐 Motivation**

Scopelift's [Flexible Voting extension](https://flexiblevoting.com/) ([github](https://github.com/ScopeLift/flexible-voting)) has been live for ~1.5 years. Several Governor implementations use it (Frax, Gitcoin, and PoolTogether) with more in the pipeline (Wormhole, Arbitrum, RadWorks). 

The extension supports several new use cases, such as voting from a [DeFi protocol](https://scopelift.co/blog/how-scopelift-built-a-flex-voting-atoken-on-aave) and [multichain voting](https://github.com/ScopeLift/l2-flexible-voting). I have also talked to projects interested in building private voting or liquid delegation features on top of Flexible Voting. 

I would be in favor of merging the Flexible Voting Extension into OZ Governor contracts to solidify the standard and make it easier for builders to build new use cases.  I understand that there are other possible standards for fractional voting, but this one seems to be the one with by far the most traction.

**📝 Details**
The changes to support Flexible Voting are in [this repository](https://github.com/ScopeLift/flexible-voting/blob/master/src/GovernorCountingFractional.sol). If there is interest in this proposal, the ScopeLift team would probably be able to help advise on next steps for merging the code.

**Comment by apbendi** [comment]
Hello, Ben from ScopeLift here 👋 

Thanks, @rsolari, for suggesting this and notifying me that you had. Unsurprisingly, we are in favor of this be included in OZ. We see growing interest in Flexible Voting and the kinds of integrations it enables. I just wanted to add that we already [have a PR](https://github.com/ScopeLift/flexible-voting/pull/66) upgrading the extension to work with OZ v5. We would be more than happy to migrate this to a PR against the main contracts repo and to work with the OZ team to integrate any feedback they would have to get it where it needs to be in order to be merged. Thanks in advance for the consideration!

**Comment by rsolari** [comment]
Yes, GovernorCountingFractional would unlock the use cases I have in mind!

**Comment by ernestognw** [comment]
For the record, [this question came to the forum](https://forum.openzeppelin.com/t/erc20votes-liquidity-pools-and-dead-address/40098) asking for the effect of delegations when depositing to a liquidity pool.
