### ISSUE TITLE
ERC1967Utils and/or UUPSUpgradeable should enforce that only ADMIN is allowed to upgrade the implementation

### ISSUE THREAD

**Issue by yaronvel** [OpenZeppelin/openzeppelin-contracts#5016]
[EIP1967](https://eips.ethereum.org/EIPS/eip-1967) dictated that:
```
Admin address
Storage slot 0xb53127684a568b3173ae13b9f8a6016e243e63b6e8ee1178d6a717850b5d6103 (obtained as bytes32(uint256(keccak256('eip1967.proxy.admin')) - 1)).

Holds the address that is allowed to upgrade the logic contract address for this proxy (optional). Changes to this slot SHOULD be notified by the event:

event AdminChanged(address previousAdmin, address newAdmin);
```

However this is not enforced neither [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol#L126) nor [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/ERC1967/ERC1967Utils.sol#L68).

**Comment by ernestognw** [comment]
Hey @yaronvel, it's not clear what is not being enforced since the EIP paragraph references multiple things. Given the title of the issue, I'll assume you're arguing that the address in the admin slot is not enforced to be the only upgrader.

As you may notice, the EIP doesn't use "MUST" in the sentence and is also very clear about it being optional:

> Holds the address that is allowed to upgrade the logic contract address for this proxy (optional).

Yet, both references are incomplete. The first is a virtual function with instructions to override and the second is an internal function in a library (i.e. not exposed publicly and frequently wrapped with some sort of access control). It's the developer's responsibility to keep the allowed upgrader address in the corresponding slot and emit its events, though it's not enforceable and therefore strongly suggested with:

> Changes to this slot SHOULD be notified by the event

Closing. Feel free to ask questions in our [community forum](https://forum.openzeppelin.com/), but please review our [support standards](https://forum.openzeppelin.com/t/how-do-i-ask-a-good-question/9375)
