### ISSUE TITLE
Create2 doesn't bubble up returndata on revert

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#5046]
When a contract deployment fails in `Create2`, returndata is ignored even though it may contain a revert reason that should probably be bubbled up like the `Address` library does for calls. I haven't checked if Solidity does this for native contract creation.

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/255e27e6d22934ddaf00c7f279039142d725382d/contracts/utils/Create2.sol#L49

**Comment by ernestognw** [comment]
Seems like it does bubble up the revert reason. I tested the following in Remix:

```solidity
pragma solidity ^0.8.24;

contract A {
    constructor() {
        revert("Some message");
    }
}

contract Test {
    constructor() {
        new A{salt:keccak256("some salt")}();
    }
}
```

The result is that `Some message` is shown in the console.

> Reason provided by the contract: "Some message".

Although it seems to be the default behavior in Solidity, this is one of those cases where bubbling up the revert reason adds an extra instruction that nobody asked for 🤔.

Although factories should rely mostly on `Clones` for deterministic deployments instead of `Create2`, I wonder if there's a use case we this extra instruction would represent significative costs.
