### ISSUE TITLE
Governor missing supported IERC721Receiver interface Id

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/openzeppelin-contracts#5261]
Shouldn't the IERC721Receiver interface be registered in Governor too?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/fe6249ec2c2dcdbb05e2b6a0d0d3e229f6ffbb37/contracts/governance/Governor.sol#L95

**Comment by Amxx** [comment]
No, 

Implementing ERC-165 and exposing the interfaceId for IERC721Receiver is not part of the ERC721 specification. 

This means:
- it cannot be expected to be present
- nobody checks for it, because it cannot be expected to be present
- its useless to expose it, because nobody checks for it, because it cannot be expected to be present
