### ISSUE TITLE
Add ERC20 support to SplitPayment

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-contracts#898]
`SplitPayment` allows a group of people to receive ether payments proportionally to their shares. The function `claim` extracts the correct amount of ether. We should add support to receive ERC20 token payments and for payees to claim them, probably through a `claim(ERC20 token)` function.

See https://github.com/OpenZeppelin/zeppelin-solidity/issues/859 for a use case.

- [x] 📈 This is a feature request.

**Comment by pw94** [comment]
Hey, I would like to code it. I have started to do it but I came accross two issues:

- Would the contract be used to maintain tokens and eth value simultaneously? If so, I should track `totalReleased` value (eth) and `tokenTotalReleased` separately as well as `released` values.
- Since to use token I need only `balanceOf` and `transfer` functions I can use sufficient _ERC20Basic_ instead of _ERC20_ in `claim` function?

**Comment by frangio** [comment]
1) You should have a `mapping (address => uint256) tokenTotalReleased` for each token address, as well as `mapping (address => mapping (address => uint256)) tokenReleased` for each token address for each account.
2) Yes you could just use ERC20Basic.

**Comment by Aniket-Engg** [comment]
@frangio This would be great if you can review the PR so that current status of issue can be known.

**Comment by nventuro** [comment]
@Aniket-Engg much has changed since that PR was opened, so some updating will need to be done. I'll try to review it during these next couple days.

**Comment by frangio** [comment]
This is part of a bigger challenge we have of uniformly handling tokens and ether in several of our contracts. We don't have a good design for this yet. Related to https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1099.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2858.
